### ISSUE TITLE
Issue with PagerScreen

### ISSUE THREAD

**Issue by Fra078** [google/horologist#1022]
Unable to use swipe dismiss gesture when implemented PagerScreen

**Comment by yschimke** [comment]
Not sure if you found the answer, but you need this modifier

https://developer.android.com/reference/kotlin/androidx/wear/compose/material/package-summary#(androidx.compose.ui.Modifier).edgeSwipeToDismiss(androidx.wear.compose.material.SwipeToDismissBoxState,androidx.compose.ui.unit.Dp)
