### ISSUE TITLE
RotaryInputAccumulator rateLimitCoolDownMs bug?

### ISSUE THREAD

**Issue by granttheyeti** [google/horologist#1035]
I have not gotten rateLimitCoolDownMs in RotaryInputAccumulator to work. Changing the values when using the AccumulatedRotaryInputModifier has no effect. When I try to debug it I believe it's because lastUpdateTimeMs is always zero when the threshold is hit. https://github.com/google/horologist/blob/6257a90b98b2368b81f93c71ed3e94e509603f0b/compose-layout/src/main/java/com/google/android/horologist/compose/rotaryinput/RotaryInputAccumulator.kt#L51

![Pasted Graphic 2](https://user-images.githubusercontent.com/71795669/221038440-81fd3994-25ad-41b9-b4d8-48908b120350.png)

My best guess is that a new RotaryInputAccumulator object is [created](https://github.com/google/horologist/blob/main/compose-layout/src/main/java/com/google/android/horologist/compose/rotaryinput/AccumulatedRotaryInputModifier.kt#L43) every time onValueChange is called which updates my view model which redraws the layout with a new modifier. Not sure though since I'm newer to compose and compose modifiers.

Here is a gist of my code: https://gist.github.com/granttheyeti/feaa2ed43dfcbc8d8f390f02e2371fdd

Could you please help me understand what's going on?

Thanks,
Grant

**Comment by yschimke** [comment]
I think we saw a similar bug because recomposes were causing a new modifier in our case we refactored slightly to avoid the recomposes, but I think we have a bug for the other one.

Let me dig that out later today.

But we should change this modifier to use composed and avoid this.

Thanks for reporting.

**Comment by yschimke** [comment]
Was fixed with a valid fix/improvement, but effectively also a workaround for this bug.

https://github.com/google/horologist/pull/989/files#diff-eb06d39aa6b043443ee9f44c6abae166c70b5e35f48e3d84911642ce5f519a27R178

Thanks for raising, I don't think we have another tracking bug.

cc @laiyichin

**Comment by yschimke** [comment]
WIP https://github.com/google/horologist/pull/1042

**Comment by granttheyeti** [comment]
Great - yeah wrapping in a **Scaffold** and using **rememberActiveFocusRequester** does seem to be a workaround. But it seems like you've submitted the fix in #1042. Thank you!
