### ISSUE TITLE
Please consider not using `DataClient` for the Auth Data library

### ISSUE THREAD

**Issue by NoahAndrews** [google/horologist#1036]
It's not immediately clear from my (very brief) look into the horologist codebase, but I suspect that the Auth Data library uses `DataClient` to sync credential tokens, since that's what Google's official guide demonstrates. If that's not accurate, then this is moot.

In my view, using `DataClient` for this purpose is a questionable choice, given that data stored using that API is synced to Google's servers, as per [this table](https://developer.android.com/training/wearables/data/data-layer#comparison-table) and the "synchronize data" section above it. I suspect it's recommended for ease of use and a user experience that works seamlessly in more situations (since it makes the data available even if the watch isn't connected to the Android phone via Bluetooth at that particular moment), but it seems to me like a significant security tradeoff for minimal benefit.

I believe the best alternative would be to use a `MessageClient` to send over the token via Bluetooth. If the user's phone isn't currently connected via Bluetooth, a prompt could be displayed informing the user that they need to connect it in order to sync credentials.

At a minimum, the fact that the auth tokens are being stored on Google's servers needs to be clearly documented (once the Auth Data module _has_ documentation anyway).

Thanks for your hard work on horologist!

**Comment by NoahAndrews** [comment]
I do suspect that in most cases, Google's `DataClient` service is likely more secure than whatever the app's main server is. However, having login data in an additional cloud server is strictly worse for security.

**Comment by yschimke** [comment]
I've raised internally the concern about uncertainty about the encryption and safety of the DataLayer and DataClient specifically internally. I'd suggest it's largely a documentation issue, but it's hollow while I can't point to docs to prove it.  Hopefully I can follow up with that in coming weeks.

I think usage of google libraries and servers for backup, authentication is widely used, and the current token sharing solution in Horologist has a lot of nice properties, if you are comfortable with tokens being stored on Google's servers. It's simple, works even while devices are not connected, and allows for seamless updates to the token that are refreshed on the mobile.

But I like where you are going with the token sharing solution.  This seems like a really nice pattern, for a one time handshake while both devices are nearby and connected, and from then on the wear app is independent.

Would you consider contributing it to Horologist in future once you've tested it out in your app?

**Comment by NoahAndrews** [comment]
> I've raised internally the concern about uncertainty about the encryption and safety of the DataLayer and DataClient specifically internally. I'd suggest it's largely a documentation issue, but it's hollow while I can't point to docs to prove it. Hopefully I can follow up with that in coming weeks.

Awesome, thanks.

> [I think] the current token sharing solution in Horologist has a lot of nice properties, if you are comfortable with tokens being stored on Google's servers. It's simple, works even while devices are not connected, and allows for seamless updates to the token that are refreshed on the mobile.

Agreed!

> But I like where you are going with the token sharing solution. This seems like a really nice pattern, for a one time handshake while both devices are nearby and connected, and from then on the wear app is independent.
>
> Would you consider contributing it to Horologist in future once you've tested it out in your app?

[I'm planning on contributing to the Pocket Casts Wear OS app](https://github.com/Automattic/pocket-casts-android/issues/468#issuecomment-1442772267) in my spare time, when I feel like it. If I end up implementing this, I'd do it with an eye towards contribution to horologist, but that's a sizable if.

> I think usage of google libraries and servers for backup, authentication is widely used

I wanted to see to what extent that was true (specifically for the authentication part), so here's what I found in Google's credential-related recommendations.

The [basic tutorial for storing account data](https://developer.android.com/training/id-auth/identify) just uses AccountManager, which to my knowledge is not synced. If it is, that's another thing that would need a very clear disclaimer added to its docs.

The [old documentation for syncing accounts to a new device](https://developer.android.com/guide/topics/data/account-transfer) uses the Account Transfer API, with a note that "the Account Transfer API will be deprecated in late 2022". The Account Transfer API documentation explicitly states that it transfers accounts directly from one device to another, with no data being sent to a third-party server:

> To add support for transferring custom accounts, integrate the Account Transfer API in your app. Google Play services can then establish a bidirectional encrypted channel between the existing device, also known as the source device, and the new device, also known as the target device, to transfer account data as illustrated in figure 2. The encrypted channel doesn't rely on being connected to third-party servers to complete the transfer.

The aforementioned deprecation note links to the new [Block Store](https://developers.google.com/identity/blockstore/android) API, which based on [The Wayback Machine](https://web.archive.org/web/20210831100705/https://developers.google.com/identity/blockstore/android) was probably only launched in 2021. Block Store *can* involve syncing credentials to Google's servers, but [the docs emphasize that you should only enable this behavior when end-to-end encryption is enabled](https://developers.google.com/identity/blockstore/android#enable-cloud-backup). I really wish that the internals of the end-to-end encryption was documented (hint hint 😉), but the implication is that Google never has access to an encryption key that is capable of decrypting the credentials. If this claim holds up to scrutiny, then there's no problem with the cloud syncing. It's entirely unclear how the decryption key gets transferred, unfortunately.

All of Google's documentation for authentication on phone apps that I found either does not involve syncing credentials to the cloud, or emphasizes the need to use end-to-end encryption when doing this. This stands in stark contrast to the Wear OS docs. Also, Block Store's end-to-end encryption requires Android 9, and I don't believe that `DataClient` has any such requirement, which implies that end-to-end encryption is not being used (or at least not *always* being used).

**Comment by yschimke** [comment]
Closing, since we have clearer security information.
