### ISSUE TITLE
Media sample app displaying album name incorrectly

### ISSUE THREAD

**Issue by luizgrp** [google/horologist#1041]
|entity screen|remove dialog|
|---|---|
|![Screenshot_20230224_124943](https://user-images.githubusercontent.com/878134/221183490-9405274e-cd68-4fc0-a1c7-9fbb314ea924.png)|![Screenshot_20230224_124955](https://user-images.githubusercontent.com/878134/221183500-bb1ce9ba-16f1-4b5f-9528-995032897350.png)|

**Comment by yschimke** [comment]
Low priority
