### ISSUE TITLE
PlayPauseButton is not animated AnimatedMediaControlButtons

### ISSUE THREAD

**Issue by kpaikena** [google/horologist#1048]
Currently in AnimatedMediaControlButtons the center button (play/pause) is not actually animated. AnimatedMediaControlButtons should be using AnimatedPlayPauseProgressButton instead of PlayPauseProgressButton so that the button uses the Lottie animations.

**Comment by yschimke** [comment]
Closing, although we may want to reopen if we find any issues in testing.
