### ISSUE TITLE
Improve WearDataLayerRegistry to check APIs availability

### ISSUE THREAD

**Issue by luizgrp** [google/horologist#1091]
Not sure you like the God object of the registry, but if we push this up there, then it can be done once, at startup meaning it's immediately available so screen can draw correctly immediately.

_Originally posted by @yschimke in https://github.com/google/horologist/pull/1089#discussion_r1133070428_

**Comment by yschimke** [comment]
Closing as low priority, reopen if keen to work on it.

**Comment by yschimke** [comment]
We should probably move away from WearDataLayerRegistry, @luizgrp convinced me it's a unneccesary approach.
