### ISSUE TITLE
Rotary modifiers should work with reverseLayout = true

### ISSUE THREAD

**Issue by yschimke** [google/horologist#1094]
> We are currently using the `.rotaryWithScroll` modifier to respond to rotary input, but I can’t find a way to get the scroll direction correct when using a `ScalingLazyColumn` with a reversed layout. Is there a workaround for this?

cc @kpeved

**Comment by Kpeved** [comment]
Checked - with a `reverseLayout = true` List is scrolled in the opposite direction. 
A possible solution for that might be an additional `reverseLayout` parameter for rotaryScroll modifiers.

**Comment by yschimke** [comment]
Let's go with that for now, and follow up after any internal API review.

**Comment by yschimke** [comment]
Fixed https://github.com/google/horologist/pull/1112
