### ISSUE TITLE
MediaCollectionsTileService throws on empty playlist

### ISSUE THREAD

**Issue by fstanis** [google/horologist#1110]
These lines rely on a few things being non-empty:

https://github.com/google/horologist/blob/de6e19842dba1de99d5861309b9d5f307669b78f/media-sample/src/main/java/com/google/android/horologist/mediasample/data/service/tile/MediaCollectionsTileService.kt#L72-L78

If that's not true, the tile throws `Caused by: java.util.NoSuchElementException: List is empty.`

We need to add a default "empty playlist" tile.

**Comment by yschimke** [comment]
cc @kul3r4

**Comment by yschimke** [comment]
Closing as low priority, reopen if keen to work on it.
