### ISSUE TITLE
Scrollbar not shown when navigating to a scrollable screen

### ISSUE THREAD

**Issue by tametter** [google/horologist#1137]
When navigating to a screen, it would be great if it was possible to force show the scrollbar to indicate to the user that the content is scrollable. This should also work in case the content is loaded asynchronously.

**Comment by yschimke** [comment]
cc @BowerSteve any advice here?

**Comment by BowerSteve** [comment]
Hi - I don't think there's currently a way to force the PI to be shown initially with a ScalingLazyColumn (I seem to recall the UX spec was that it should not be shown until scrolling occurred). However, it's possible to provide a CustomPositionIndicatorState, like in this demo, which controls the Show/Hide visibility:
https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:wear/compose/integration-tests/demos/src/main/java/androidx/wear/compose/integration/demos/PositionIndicatorDemos.kt;l=216?q=file:wear%2Fcompose%20CustomPosition&sq=&ss=androidx%2Fplatform%2Fframeworks%2Fsupport

**Comment by BowerSteve** [comment]
Functions are public by default in Kotlin - we normally state it explicitly in Wear/Material, but given that other libraries like Compose/Material omit it, we will also omit the 'public' in future APIs.

**Comment by tdnghia98** [comment]
Hi, has there been any progress on this feature? My app has got rejected by Google due to missing scrollbar when user enters the screen

**Comment by yschimke** [comment]
When did this happen? That requirement has been removed, so shouldn't have happened this week.

Can you copy the full message?

**Comment by JulienDev** [comment]
Happened again to me today:

> Issue found: Missing scrollbar
> Your app does not display the scroll bar when the user enters a scrollable view and/or when the user scrolls. For more information, see [Show the scrollbar](https://notifications.google.com/g/p/ANiao5rASisbbB7JwMBcQQ-MDsEd-W4JXQ3igV6ES5DNqDuRHfUtCzm8LpjruGZJrvTTw0l_gbEhpX6GbxSaMqtqEH1pC6OMt98f-pp543uYyjWwp3MyQoo0ilzkuSKcRPBRfGrdXzsLF0klAyrVwlMml1VwW-JYG35sUNy_tq8_Ptrx36M1IbNLGoZWwUXXNdc-v-enI6Jr8RAHbZ5IIugxVXDm-Txy-iTMo_y6D2pz2DXzR6Fxr4VnRYkeMFgzCzU41bOMHtc).
> 
> About the Wear App Quality Guidelines
> We do not accept apps into Wear OS that don't adhere to [Wear App Quality](https://notifications.google.com/g/p/ANiao5qVGnucO-ul-XZVV9bZ2SYQ091cODIOsjW7FaKl9S9ynRD8yX7f0Uny8BHbnJG3mb6tg7j59PV1ltNyWdLNLEMjvQz36VZEJhDdwCAz5oR2GPJosytJopyB1IE5MDWU9B8_OgqK61n1P33E4ixunk8pc5k7QLN8lopmCOQ_utMVu7UHfbc9XKsfW_5OgldTQT1F78WKV45ffZmouWySztvFR65xMAEdDxYrAbfLFnudgCLzQ301GoYJcyQLfJPx) Guidelines.

**Comment by yschimke** [comment]
It's likely a mistake in the text they sent. And only because of a screen with missing position indicator.

**Comment by tdnghia98** [comment]
Sorry for the late reply. Here is the rejection message

<img width="790" alt="image" src="https://github.com/google/horologist/assets/26921719/acd2c627-3cb5-4820-b39f-1e7e736b9e61">

I have then displayed the position indicator when entering the page and now they are challenging on other things. It means that this is really something that is taken into account during the approuval

**Comment by Kpeved** [comment]
ScrollBar should be showed by default in Wear Compose 1.4.0-alpha01

**Comment by HeyPouya** [comment]
Hey @Kpeved ,
I'm using the latest version of Horologist (and also tried wear compose 1.4.1), but the scroll bar is not being displayed in the ScalingLazyColumn and my app is getting rejected. Any help is appreciated.

**Comment by kul3r4** [comment]
@HeyPouya can you share sample code where you can reproduce the issues?
