### ISSUE TITLE
Enable progress bar animations

### ISSUE THREAD

**Issue by fstanis** [google/horologist#1171]
The playback progress bar supports animating progress on e.g. seek but the property that allows this is currently always false:

https://github.com/google/horologist/blob/9b2aebc52514645c8ec65723fda5b0b3de44335d/media-ui/src/main/java/com/google/android/horologist/media/ui/state/model/TrackPositionUiModel.kt#L26

This is a tracking issue to test the behavior and enable it.

**Comment by yschimke** [comment]
@fstanis seems suitable for someone new?

**Comment by yschimke** [comment]
I think this is handled in predictive. Reopen if still needed.
