### ISSUE TITLE
Unable to start a list from a non-first Page mixing horologist and Paging 3

### ISSUE THREAD

**Issue by Fra078** [google/horologist#1188]
Using horologist scalingLazyColumn with his state doesn't allow to display a list from a custom page from collectAsLazyPaging items. When list Is created there is immediately a jump to the first list item

**Comment by yschimke** [comment]
Are you wanting to pass it into the factories like `belowTimeText()`

https://github.com/google/horologist/blob/32feb2f34a5bb333b91786b594fe7486796d163b/compose-layout/src/main/java/com/google/android/horologist/compose/layout/ScalingLazyColumnDefaults.kt#L44

Or is there something specific to paging?

**Comment by Fra078** [comment]
I mean that by setting a starting page other than the first, the column tries to bring the index of scroll position to 0

**Comment by yschimke** [comment]
Is this inside PagerScreen (HorizontalPager) or Navigation? Do you have a simple example, oor adjust the current sample https://github.com/google/horologist/blob/5f8f1fd8cbc5236f2722b062ddb75f1c96929f46/sample/src/main/java/com/google/android/horologist/paging/PagingScreen.kt#L38

**Comment by yschimke** [comment]
No repro
