### ISSUE TITLE
Can uses-feature watch be removed from network-awareness library?

### ISSUE THREAD

**Issue by mchowning** [google/horologist#1200]
It would be nice to be able to add the network-awareness module to modules that are shared by a phone and watch app. Because the network-awareness library's [manifest file specifies that it uses watch features](https://github.com/google/horologist/blob/main/network-awareness/src/main/AndroidManifest.xml#L22), building an app that transitively depends on network-awareness for a phone results in Android Studio presenting a "missing feature: WATCH" pop-up warning.

Does the network-awareness library only work with a watch or could the `uses-feature`-watch line be removed from the network-awareness library's manifest file (which would make it easier to use this library in shared modules)?

**Comment by mchowning** [comment]
If it is possible to use depend on this module within a phone app, would it also make sense to drop the minSdk to from 26 to 23, like [was recently done on some of the other modules that can be used on phones](https://github.com/google/horologist/commit/b6227070ffe0dd30c3f4a2539e267cf29e0b10e8)?

My app's min SDK is currently 23, so I'm not exactly unbiased in making this suggestion 😉. (we are due to increase our min sdk, but I don't think we'll be raising it to 26).

**Comment by yschimke** [comment]
I'll need to split out the UI components.  But it feels like a good time to do that.

**Comment by yschimke** [comment]
Should be fixed in 0.4.3, but wouldn't be surprised if I missed something.

https://github.com/google/horologist/releases

It's now 4 modules to avoid a wear dependency 

network-awareness
network-awareness-db
network-awareness-okhttp
network-awareness-ui (with wear dependencies)
