### ISSUE TITLE
Implement StandardSplitToggleChip

### ISSUE THREAD

**Issue by luizgrp** [google/horologist#1318]
Implement `StandardSplitToggleChip`.

<details><summary>Redlines</summary>
<p>

![Screenshot 2023-05-26 at 15 37 49](https://github.com/google/horologist/assets/878134/5526cde7-800e-494f-932c-b305593872ce)

![Screenshot 2023-05-26 at 15 37 28](https://github.com/google/horologist/assets/878134/937fc645-ee51-4e12-80cc-2929458bb613) ![Screenshot 2023-05-26 at 15 37 35](https://github.com/google/horologist/assets/878134/620f3f5e-7e77-485c-bf09-f24a3069fd93)

</p>
</details> 

Should be similar to what was implemented for `StandardToggleChip` in https://github.com/google/horologist/pull/1283 and https://github.com/google/horologist/pull/1286.

Expected output:
- Implementation in `base-ui` module, matching the redlines;
- Previews in the `debug` folder for each variant;
- Snapshot tests for:
   - each variant;
   - text overflow;
   - large font scale (`TestHarness(fontScale = 1.18f))`);
   - rtl (`TestHarness(layoutDirection = LayoutDirection.Rtl))`);

**Comment by DenoRS** [comment]
Hey, happy to pick this up :)
