### ISSUE TITLE
[Tiles] Compilation fails for Hilt AndroidEntryPoint on service extending SuspendingTileService

### ISSUE THREAD

**Issue by Ethan1983** [google/horologist#1320]
Compilation fails when Hilt is used for dependency injection on TileService extending `SuspendingTileService`

```
error: cannot access ListenableFuture
public abstract class Hilt_SampleTileService extends SuspendingTileService implements GeneratedComponentManagerHolder {
                ^
  class file for com.google.common.util.concurrent.ListenableFuture not found
```

Note: fails only when `com.google.android.horologist:horologist-compose-tools` dependency is added.

**Comment by yschimke** [comment]
Thanks, as a workaround, you might need an explicit dependency on coroutines-guava or guava itself.

Could you attach the output of `./gradlew app:dependencies` so I can see why.

**Comment by Ethan1983** [comment]
@yschimke Tried adding an explicit dependency but that didn't help. Here is a minimal reproducible project, https://github.com/Ethan1983/TileHiltApp

**Comment by luizgrp** [comment]
Add the following dependency and it should fix it:

```
implementation "org.jetbrains.kotlinx:kotlinx-coroutines-guava:1.7.1"
```

**Comment by Ethan1983** [comment]
> Add the following dependency and it should fix it:
> 
> ```
> implementation "org.jetbrains.kotlinx:kotlinx-coroutines-guava:1.7.1"
> ```

Thanks for the quick fix, can confirm it works.
