### ISSUE TITLE
Add Compose Material library

### ISSUE THREAD

**Issue by luizgrp** [google/horologist#1324]
### WHAT

Add Horologist Compose Material library.

### WHY

In order to provide components built on the core AndroidX library, to remove boilerplate and to add opinionated a11y support.

### HOW
- https://github.com/google/horologist/pull/1327;
- [x] Copy components from `base-ui` to `compose-material` module, changing the package name;
   - [x] Change component names to match the ones in wear-compose;
   - [x] Keep components in `base-ui` for few releases, marked as deprecated, suggesting the new library;
   - [x] Change the code of the components in `base-ui` to use the ones from `compose-material`;
   - [x] Remove previews from `base-ui`, keep the unit tests to check if the usage of `compose-material` is correct;
- [ ] Add new components TBD;
   - https://github.com/google/horologist/issues/1318
   - https://github.com/google/horologist/issues/1346
   - https://github.com/google/horologist/issues/1396
   - https://github.com/google/horologist/issues/1397
   - https://github.com/google/horologist/issues/1398
   - https://github.com/google/horologist/issues/1411
- https://github.com/google/horologist/issues/1347;
- https://github.com/google/horologist/pull/1392;
- https://github.com/google/horologist/pull/1492;

**Comment by yschimke** [comment]
Closing as completed in favour of individual issues.
