### ISSUE TITLE
Improve ScreenshotBaseTest

### ISSUE THREAD

**Issue by luizgrp** [google/horologist#1335]
### WHAT

Improve `ScreenshotBaseTest` to allow it to set the parameters in a more convenient way, without requiring to call and import `screenshotTestRuleParams`. For example:

```kotlin
class MyTest : ScreenshotBaseTest({
    screenTimeText = {}
    enableA11y = true
}) {
```

### WHY

Feedback on usage https://github.com/google/horologist/pull/1312#discussion_r1205741849

### HOW

_Suggestion_ of implementation with [type safe builders](https://kotlinlang.org/docs/type-safe-builders.html).

**Comment by yschimke** [comment]
We should probably also pick up the record default value from a system property so we can run tests in a record mode, and not edit the files.
