### ISSUE TITLE
Improve Title component

### ISSUE THREAD

**Issue by luizgrp** [google/horologist#1346]
Improve `Title` component to have the variants listed in the [Material Design kit](https://developer.android.com/design/ui/wear/guides/foundations/download).

<details><summary>Redlines</summary>
<p>

![Screenshot 2023-06-01 at 10 26 56](https://github.com/google/horologist/assets/878134/9385ff99-9a91-4dda-8edf-ddf495da21eb)

![Screenshot 2023-06-01 at 10 31 57](https://github.com/google/horologist/assets/878134/e70c7867-0c89-4559-a483-7a12e05fe4b2)

</p>
</details> 

Expected output:
- Implementation in `compose-material` module, matching the redlines;
- Previews in the `debug` folder for each variant;
- Snapshot tests for:
   - each variant;
   - text overflow;

**Comment by DenoRS** [comment]
@luizgrp happy to pick this up :)
