### ISSUE TITLE
Add TextField in compose-material

### ISSUE THREAD

**Issue by Fra078** [google/horologist#1355]
Currently wear material compose haven't added a corresponding TextField composable

**Comment by yschimke** [comment]
It's by design, you should launch out to get input

See https://github.com/android/wear-os-samples/blob/main/ComposeAdvanced/app/src/main/java/com/example/android/wearable/composeadvanced/presentation/ui/userinput/UserInputComponentsScreen.kt

**Comment by Fra078** [comment]
I know that text input should be launched by a button, RemoteInput APIs are limited. I can't decide input type (an example is putting password or  putting a phone number) it displays always keyboard with characters and

**Comment by yschimke** [comment]
It won't get fixed here in Horologist - suggest you comment on https://buganizer.corp.google.com/issues/213546115

I guess what we could do, it create a non editable BasicTextField, that when clicked calls out to GBoard so API wise its similar to BasicTextField.  I don't think it helps you with input type, but it's not our remit to build out platform components like text fields.
