### ISSUE TITLE
Cannot disable Haptic feedback on ScalingLazyColumn rotary input

### ISSUE THREAD

**Issue by Fra078** [google/horologist#1383]
There isn't an option to disable haptic feedback when using rotaryWith** modifiers

**Comment by yschimke** [comment]
https://github.com/google/horologist/blob/main/compose-layout/src/main/java/com/google/android/horologist/compose/rotaryinput/Haptics.kt#L194

`rememberDisabledHaptics()`

**Comment by yschimke** [comment]
That makes sense. This wasn't clear from your original issue.

**Comment by Fra078** [comment]
> That makes sense. This wasn't clear from your original issue.

I checked ScalingLazyColumn code, I noticed that ScalingLazyColumnState.reversed isn't passed to modifierWithRotary so scrolling with rotary on reversed columns is not as user expects.

**Comment by yschimke** [comment]
Draft PR https://github.com/google/horologist/pull/1389

**Comment by yschimke** [comment]
Should be fixed in next release
