### ISSUE TITLE
Implement CompactChip

### ISSUE THREAD

**Issue by luizgrp** [google/horologist#1396]
Implement `CompactChip`.

<details><summary>Redlines</summary>
<p>

![Screenshot 2023-06-14 at 15 52 47](https://github.com/google/horologist/assets/878134/c5e72fb4-a4e8-429c-9807-3b7908b918eb)

</p>
</details> 

Expected output:
- Implementation in `compose-material` module, matching the redlines;
- Implementation should use [CompactChip](https://github.com/androidx/androidx/blob/f82d8680186b38cb99b8c3f3993ed2b12b335f1d/wear/compose/compose-material/src/main/java/androidx/wear/compose/material/Chip.kt#L520) from wear compose material library;
- Previews in the `debug` folder for each variant;
- Snapshot tests for:
   - each variant;
   - text overflow;
   - large font scale (`TestHarness(fontScale = 1.18f))`);
   - rtl (`TestHarness(layoutDirection = LayoutDirection.Rtl))`);
   - a11y

**Comment by MohitMandalia** [comment]
Can I help in implementing this one?
