### ISSUE TITLE
Implement OutlinedChip

### ISSUE THREAD

**Issue by luizgrp** [google/horologist#1398]
Implement `OutlinedChip`.

<details><summary>Redlines</summary>
<p>

![Screenshot 2023-06-14 at 16 03 31](https://github.com/google/horologist/assets/878134/549d9023-72f7-4943-89fd-b16dec758bf6)

</p>
</details> 

Expected output:
- Implementation in `compose-material` module, matching the redlines;
- Implementation should use [OutlinedChip](https://github.com/androidx/androidx/blob/f82d8680186b38cb99b8c3f3993ed2b12b335f1d/wear/compose/compose-material/src/main/java/androidx/wear/compose/material/Chip.kt#L420) from wear compose material library;
- Previews in the `debug` folder for each variant;
- Snapshot tests for:
   - each variant;
   - text overflow;
   - large font scale (`TestHarness(fontScale = 1.24f))`);
   - rtl (`TestHarness(layoutDirection = LayoutDirection.Rtl))`);
   - a11y

**Comment by uiltonjose** [comment]
I'm happy to take this one ☺️

**Comment by MohitMandalia** [comment]
I can work on this, Do we need the same as the Chip or need API's similar to the CompactChip where Icon and contentDescription was mandatory.

**Comment by luizgrp** [comment]
Nice, thanks! 
Same as `Chip`, please. `CompactChip` had content description mandatory only for the "icon only" version, which this component doesn't have.

**Comment by MohitMandalia** [comment]
Sure I will make it same as the Chip, if there are changes in the API we can refactor it after I raise the PR
Thanks

**Comment by MohitMandalia** [comment]
@luizgrp do we need a version of ChipPreviewWithImageBackgroundChipColors for OutlinedChip no right?
