### ISSUE TITLE
Implement ToggleButton

### ISSUE THREAD

**Issue by luizgrp** [google/horologist#1411]
Implement `ToggleButton`.

<details><summary>Redlines</summary>
<p>

<img width="894" alt="Screenshot 2023-06-16 at 16 00 40" src="https://github.com/google/horologist/assets/878134/d3d908be-a992-4673-8e20-37b974340f13">

<img width="836" src="https://github.com/google/horologist/assets/878134/98b0c02a-30cb-4240-a126-3a77b26affa8">

</p>
</details> 

Expected output:
- Implementation in `compose-material` module, matching the redlines;
- Implementation should use [ToggleButton](https://github.com/androidx/androidx/blob/f82d8680186b38cb99b8c3f3993ed2b12b335f1d/wear/compose/compose-material/src/main/java/androidx/wear/compose/material/ToggleButton.kt#L85) from wear compose material library;
- Should provide a convenient way to pass the icons for checked and unchecked states;
- Should provide a convenient way of passing the string for the text variant;
- Previews in the `debug` folder for each variant;
- Snapshot tests for:
   - each variant;
   - text overflow;
   - large font scale (`TestHarness(fontScale = 1.18f))`);
   - rtl (`TestHarness(layoutDirection = LayoutDirection.Rtl))`);
   - a11y

**Comment by jibranabsarulislam** [comment]
on it! I'll circle back with progress and open a PR later today

**Comment by jibranabsarulislam** [comment]
i'm sorry, it seems to be taking longer than I anticipated to get familiar and to implement the toggle. i'll update with any blockers and progress as i work it out

**Comment by yschimke** [comment]
You never need to apologise, contributions are appreciated, not homework.
