### ISSUE TITLE
dagger.hilt.android.plugin was not found in any of the following sources

### ISSUE THREAD

**Issue by theGeekyLad** [google/horologist#1421]
I cloned the repo and have been trying to simply load the media/sample project into Android Studio but see the following app Gradle build error:

```
Build file '/Users/.../MediaSample/app/build.gradle.kts' line: 22

Plugin [id: 'dagger.hilt.android.plugin'] was not found in any of the following sources:

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
```

Any suggestions to fix this?

**Comment by yschimke** [comment]
Have you opened the entire project? Or just one directory?

you should have something like this

<img width="297" alt="image" src="https://github.com/google/horologist/assets/231923/0477574b-f528-4798-a340-becd0ab734e7">

**Comment by yschimke** [comment]
reopen if this was not the issue.
