### ISSUE TITLE
Lack of documentation on important classes such as MediaPlayerScaffold

### ISSUE THREAD

**Issue by theGeekyLad** [google/horologist#1455]
I'm trying to integrate the Horologist media player classes with my project but it's super difficult without documentation. As of now, the sample project is the only ray of hope but then again, without documentation or "guides" (like how the OG Android Developers website has), it's hard to make sense out of classes or just how things are wired.

For example, exploring the sample project, I came across the `MediaPlayerScaffold` which _seems to me_ is the media player widget with various playback controls. Nonetheless, I can't read more about this class as the [link to its documentation](https://google.github.io/horologist/api/media-ui/com.google.android.horologist.media.ui.navigation/-media-player-scaffold.html) is broken.

Maybe I'm not looking in the right place. Any advice will be helpful!

**Comment by luizgrp** [comment]
Hi, thanks for the feedback.

The link that you are trying to access is [this](https://google.github.io/horologist/api/media/ui/com.google.android.horologist.media.ui.navigation/-media-player-scaffold.html) (the issue with the documentation is being tracked in https://github.com/google/horologist/issues/1256).

I'd suggest, perhaps, that you to start with this [guide](https://google.github.io/horologist/simple-media-app-guide/), if you haven't already?

**Comment by yschimke** [comment]
We are also on kotlinlang slack in the compose-wear. Going to close this as that PR has landed.
