### ISSUE TITLE
Default max volume is very low?

### ISSUE THREAD

**Issue by zxzxwu** [google/horologist#1556]
I am trying to make a small player app following the guide: https://google.github.io/horologist/simple-media-app-guide/
However, when I try to scroll the crown(on Pixel Watch) and change the volume, the volume is set to a very low value because the maxVolume shown in logcat is like:

```
08-08 16:26:20.040  4079  4079 D HorologistAudioUi: maxVolume=1
08-08 16:26:20.040  4079  4079 D HorologistAudioUi: change=56.9088, currentVolume=0, targetVolume=1 
08-08 16:26:20.096  4079  4079 D HorologistAudioUi: maxVolume=1
08-08 16:26:20.096  4079  4079 D HorologistAudioUi: change=58.406403, currentVolume=0, targetVolume=1 
08-08 16:26:20.146  4079  4079 D HorologistAudioUi: maxVolume=1
08-08 16:26:20.146  4079  4079 D HorologistAudioUi: change=49.4208, currentVolume=0, targetVolume=1 
08-08 16:26:20.413  4079  4079 D HorologistAudioUi: maxVolume=1
08-08 16:26:20.413  4079  4079 D HorologistAudioUi: change=-74.88, currentVolume=0, targetVolume=0 
08-08 16:26:20.436  4079  4079 D HorologistAudioUi: maxVolume=1
08-08 16:26:20.436  4079  4079 D HorologistAudioUi: change=-62.899197, currentVolume=0, targetVolume=0 
08-08 16:26:20.464  4079  4079 D HorologistAudioUi: maxVolume=1
08-08 16:26:20.465  4079  4079 D HorologistAudioUi: change=-77.8752, currentVolume=0, targetVolume=0 

```

Did I do anything wrong? My code is like:

```kt
private fun createVolumeViewModel(): VolumeViewModel {
    val audioRepository = SystemAudioRepository.fromContext(application)
    val vibrator: Vibrator = application.getSystemService(Vibrator::class.java)

    return VolumeViewModel(
      audioRepository,
      audioRepository,
      onCleared = { audioRepository.close() },
      vibrator
    )
  }
```

**Comment by laiyichin** [comment]
Hi, It looks like the VolumeUiState might not be emitting correctly and is using the default value. Can you inspect to see if volume state in your audioRepository?

[](https://github.com/google/horologist/blob/29edb1069be6b536028ccb869ff6215655c364ca/media/audio-ui/src/main/java/com/google/android/horologist/audio/ui/VolumeUiState.kt#L24)

https://github.com/google/horologist/blob/29edb1069be6b536028ccb869ff6215655c364ca/media/audio-ui/src/main/java/com/google/android/horologist/audio/ui/VolumeViewModel.kt#L64-L69

Alternatively, luizgrp@ has a sample app that you can try cloning and running to see if the RSB volume change is working as expected?
https://github.com/luizgrp/HorologistSimpleMediaAppGuide

**Comment by zxzxwu** [comment]
`volumeState`s from audioRepository are reported correctly with `max=15`(and note that I am using `com.google.android.horologist.audio.SystemAudioRepository`), changes are also reflected.

**Comment by luizgrp** [comment]
For future reference, I could also reproduce the issue with the code from the simple media app guide using this [repo](https://github.com/luizgrp/HorologistSimpleMediaAppGuide/tree/functional) after updating Horologist to `0.5.3` from `0.4.5`. In `0.4.5` the issue was not present.

**Comment by yschimke** [comment]
Such a subtle bug, I reviewed it at the time, and even looking at the PR again just thought it was fine.  But using the viewModel StateFlow doesn't trigger compose state tracking.
