### ISSUE TITLE
Make Seconds optional in TimePickers

### ISSUE THREAD

**Issue by JohnNichol** [google/horologist#159]
Time pickers have hours minutes and seconds currently with no way to disable seconds - make seconds optional as hours & minutes and hours, minutes and seconds are both useful combinations

**Comment by Hirdey-1999** [comment]
I Can Go With The Issue But I Need Some Mentoring To Solve The Issue

**Comment by yschimke** [comment]
@Hirdey-1999 Sorry we missed this, I believe John already has an implementation of this in an internal repo, so it doesn't make sense for you to start on this.

In future I'll take issues that are reasonably appropriate for first time committers to Horologist with the "good first issue" label. This would have been one, but I missed your comment.

**Comment by yschimke** [comment]
https://github.com/google/horologist/pull/194
