### ISSUE TITLE
Startupbenchmark fails with IllegalStateException

### ISSUE THREAD

**Issue by DirajHS** [google/horologist#1595]
Continuing to the discussion from https://github.com/android/performance-samples/issues/212#issuecomment-1687473480, I was able to run the test on a watch for `StartupBenchmark`, which is failing. The app opens and crashes.

 Here's the error with stacktrace:

![Screenshot 2023-08-22 at 3 18 39 PM](https://github.com/android/performance-samples/assets/4804911/a50cacbf-9517-49ff-a0d3-54d99375fa8f)

**Comment by yschimke** [comment]
There is some earlier error you'll need to find from logs. That's causing this later error.

**Comment by yschimke** [comment]
Fixed by releases.
