### ISSUE TITLE
In Time/Date Pickers, use the Button to step through the columns before it becomes a 'commit'

### ISSUE THREAD

**Issue by BowerSteve** [google/horologist#160]
I think it would be good for the Button on the multi-picker screens to step through the pickers. For example, start on Day and offer '>', and clicking takes you to the Month (stays as a '>'), then when you click onto the Year, it changes to the Check icon and commits the choice.

**Comment by MohitMandalia** [comment]
Hi @yschimke is this something to be picked up?

It would look something like this, when user clicks it moves forward and if user turns back by clicking on date or any other control it again changes to >, let me know if this is something to be done.

Thanks

<img width="335" alt="Screenshot 2022-09-30 at 8 01 48 AM" src="https://user-images.githubusercontent.com/36087806/193177679-4ac22caf-70a8-4a8d-91b3-c38e80bc28f2.png">

**Comment by yschimke** [comment]
I'll check if we have an existing figma for this, but essentially yes.

**Comment by MohitMandalia** [comment]
> I'll check if we have an existing figma for this, but essentially yes.

Sure please check and let me know I'll raise a PR if its okay.

**Comment by yschimke** [comment]
@MohitMandalia I checked, we do have Figma, but internally we also have an implementation of this, so we will likely just refresh the implementation here from the internal one.  So no sense, tackling again.

**Comment by MohitMandalia** [comment]
Hmm so I guess no input is needed here from my end @yschimke

**Comment by yschimke** [comment]
Out of data given recent changes
