### ISSUE TITLE
Integrate media sample app with media3 unsuitable output playback suppression solution

### ISSUE THREAD

**Issue by anubhavkakkar** [google/horologist#1616]
Integrate media sample app with media3 unsuitable output playback suppression solution:

a) ExoPlayer.setSuppressPlaybackOnUnsuitableOutput (https://github.com/androidx/media/blob/79f96de4a5f5f85670ebb89a7f57eed6ce25c066/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/ExoPlayer.java#L736)
b) WearUnsuitableOutputPlaybackSuppressionResolverListener (https://github.com/androidx/media/blob/79f96de4a5f5f85670ebb89a7f57eed6ce25c066/libraries/ui/src/main/java/androidx/media3/ui/WearUnsuitableOutputPlaybackSuppressionResolverListener.java)

**Comment by yschimke** [comment]
Completed
