### ISSUE TITLE
Update copyright check for gradle build files

### ISSUE THREAD

**Issue by luizgrp** [google/horologist#1639]
this reminded me that we don't have groovy files anymore since they were ported to kotlin dsl, so [this](https://github.com/google/horologist/blob/9726603e4a54b803fa0ca58345189301416fda44/build.gradle.kts#L100-L108) should be updated to validate the kts files

_Originally posted by @luizgrp in https://github.com/google/horologist/pull/1638#discussion_r1312904788_

**Comment by Ao-senXiong** [comment]
@luizgrp Hi, is this issue still open and can I work on this issue?

**Comment by luizgrp** [comment]
@Ao-senXiong still open - yes, please!
