### ISSUE TITLE
Tiles emoji broken on documentation

### ISSUE THREAD

**Issue by yschimke** [google/horologist#165]
https://google.github.io/horologist/#tiles
<img width="341" alt="image" src="https://user-images.githubusercontent.com/231923/168469134-44a41e06-caa0-4063-a643-13c6e15b6dae.png">

**Comment by MohitMandalia** [comment]
couldn't find index.md was it renamed or removed?

**Comment by MohitMandalia** [comment]
Tiles emoji seems to be not supported for most platforms should we just put an image for that?

**Comment by yschimke** [comment]
Would an image render ok? Or find an alternative character to use? The others seem to work.

**Comment by MohitMandalia** [comment]
Ok i'll check , can you suggest me which emoji we are targeting here so that I could find some alternatives 
is this the once we are targeting? [Tile](https://emojipedia.org/frame-with-tiles/)

**Comment by yschimke** [comment]
Yep, but feel free to be creative. If you get stuck, let me know.

**Comment by MohitMandalia** [comment]
sure

**Comment by MohitMandalia** [comment]
would a block work ? █  or something like what is there in the git repo readme page ☰?

**Comment by yschimke** [comment]
Second looks good.

**Comment by MohitMandalia** [comment]
should we also change it in the git hub repo readme file?

**Comment by yschimke** [comment]
This is the script that generates docs.  I haven't edited it much because it comes from accompanist.

https://github.com/google/horologist/blob/98ccc7dc0f096f7d848d5b971f7a1bf53acb4620/generate_docs.sh#L33

If you note it copies the readme from the github project, during doc generation.

So I think that is the one to update.  Then I can republish the docs.

But look for any other places it is used.

**Comment by MohitMandalia** [comment]
so should update the readme instead and it will be copied to the docs.

**Comment by yschimke** [comment]
Yep.

**Comment by MohitMandalia** [comment]
Tiles icon is used only once in this project : while in the gh pages it is used 2 times one in `Table of Contents` another in the main heading so I hope table of contents are also generated from titles.

**Comment by yschimke** [comment]
@MohitMandalia Thanks for the attention on this.  I'll try to be more thoughful on issues for issues others are picking up.  But if you find something unclear, feel free to ask for more information.

**Comment by MohitMandalia** [comment]
sure Thanks

**Comment by yschimke** [comment]
Looks good https://google.github.io/horologist/

**Comment by MohitMandalia** [comment]
Yes 👍
