### ISSUE TITLE
Use LocalDensity.current.fontScale instead of LocalConfiguration.fontScale to retrieve font scale

### ISSUE THREAD

**Issue by Fra078** [google/horologist#1668]
Trying to implement custom font scale on my application I noticed that horologist material library uses the value stored in LocalConfiguration instead of LocalDensity which is used by all compose libs and can be used also on Compose Multiplatform

**Comment by yschimke** [comment]
Is it worth submitting a PR?

**Comment by Fra078** [comment]
Yes, it's important to maintain a single source of Truth avoiding future

**Comment by yschimke** [comment]
I don't see where fontScale is used that way.  Only screenHeightDp, and I don't see alternatives.
