### ISSUE TITLE
Media sample code is too complicated

### ISSUE THREAD

**Issue by Digipom** [google/horologist#1691]
I'm migrating from horologist 0.2.7 to 0.5.6, and there are a lot of breaking changes in the media libraries so I'm starting from the basics and looking at the sample code as a reference. However, the current sample is very complex with dependency injection, a browser service, different data sources and so on.

As a future enhancement, I would like to request something simple that shows: 
a) Using a service to enable background playback (but not a browser service)
b) The proper place to prepare the player and release it (it seems this was removed from PlayerRepositoryImpl)
c) Proper way to handle updating elapsed time (I used to do this with a coroutine that manually updated the time, but it seems this is done very differently now).
And so on. Just using the library simply. This will help us accommodate future breaking changes.

**Comment by yschimke** [comment]
We made a deliberate decision to build the sample around the Google promoted options like Hilt. We previously avoided this in our samples, and we found that we ended up inventing a lot of DI concepts in the sample to fill gaps, overall was not simple either.

Some specifics:

> prepare the player and release it (it seems this was removed from PlayerRepositoryImpl)

This has moved into Hilt, this lifecycle code is easy to get wrong, and once you are injecting it, it's hard to know what the tear down involves.

This is the code https://github.com/google/horologist/blob/aa6151a8b04f4da0249becc0d6b9eaa9955b47e6/media/sample/src/main/java/com/google/android/horologist/mediasample/di/PlaybackServiceModule.kt#L232

> Using a service to enable background playback (but not a browser service)

There are better examples that show the direct use of Media3 types, such as 

https://github.com/androidx/media/blob/3f366109b7e5cbf7b7e5b46e8b923e167e9ae893/demos/session/src/main/java/androidx/media3/demo/session/PlaybackService.kt#L88

> Proper way to handle updating elapsed time

This has changed to a Compose first method, see here https://github.com/google/horologist/blob/aa6151a8b04f4da0249becc0d6b9eaa9955b47e6/media/ui/src/main/java/com/google/android/horologist/media/ui/components/animated/AnimatedPlayPauseButton.kt#L236

So we read the position, status, and playback speed and predict the position for each frame.  

Thanks for the feedback, I'll leave this open and discuss how we can better document this.

**Comment by yschimke** [comment]
cc @kul3r4 for feedback

**Comment by Digipom** [comment]
Now that I've finished the migration, the main sticking points for me were:

1) Migrating from a custom PlayerRepositoryImpl to a standard one (I was able to just delete it, use the built-in one and migrate the prepare and release code to my view model)
2) Updating the UI for the changes and handling time updates -- your comments helped me out a lot here.
```
mediaDisplay = { playerUiState ->
                    val timestampProvider = LocalTimestampProvider.current
                    var position by remember { mutableStateOf(null as Duration?) }
                    val summary = position?.let {
                        DateUtils.formatElapsedTime(it.inWholeSeconds)
                    } ?: ""
                    TextMediaDisplay(
                        title = "",
                        subtitle = summary
                    )

                    LaunchedEffect(playerUiState.trackPositionUiModel) {
                        when (val state = playerUiState.trackPositionUiModel) {
                            is TrackPositionUiModel.Actual -> position = state.position
                            TrackPositionUiModel.Hidden -> position = null
                            is TrackPositionUiModel.Loading -> {
                                // Ignore -- don't erase previous value.
                            }

                            is TrackPositionUiModel.Predictive -> {
                                while (isActive) {
                                    val timestamp = timestampProvider.getTimestamp()
                                    val duration = state.predictor.predictDuration(timestamp)
                                    position = state.predictor.predictPosition(timestamp)
                                        .coerceAtMost(duration)
                                    delay(1000)
                                }
                            }
                        }
                    }
                },
```).

I didn't have to modify the rest of the integration, but I think it would still be beneficial to have a simpler example showing how to use the framework for playing a single file out of a playlist.

**Comment by yschimke** [comment]
Going to close this, as I don't think we have plans for another media sample.  And I think a real media player using remote content, DI, is more useful for this if we have to choose one.  So it's a choice.

But please ask on slack if you are stuck.
