### ISSUE TITLE
DatePicker day position issue

### ISSUE THREAD

**Issue by luizgrp** [google/horologist#179]
#### Issue

The day picker is not keeping the position of the previously selected day when going to the month picker and coming back to the day picker.

#### Steps to reproduce

There are few ways of reproducing it, as you can see in the gif attached below, but here is one:

1) Pick Jan as month
2) Pick 31 as day
3) Pick Feb as month; day should change automatically to 28
4) Go back to day picker; do not scroll or pick another day
5) Pick Jan as month
6) Go back to day picker

##### Expected result

Day picker should display day 28.

##### Actual result

Day picker displays day in between 30 and 31.

#### Video

![picker glitch](https://user-images.githubusercontent.com/878134/169016801-2150a797-47a2-4e01-811a-6a9a9a19729b.gif)

**Comment by luizgrp** [comment]
cc: @BowerSteve

**Comment by BowerSteve** [comment]
Thanks for raising this issue - I can reproduce it locally with Compose for Wear OS beta01, and I believe it is fixed in beta02 which will be released shortly. The fix is part of a change to allow switching columns by scrolling, not just tapping the other Pickers.
