### ISSUE TITLE
Check correct mirroring logic

### ISSUE THREAD

**Issue by yschimke** [google/horologist#1796]
Here the icon is not mirrored when it should. But it makes me think if this actually exposing an issue either:
- with our Icon implementation, when receiving "AutoMirrored" icons, it should not scale.
- with our test code, when using "AutoMirrored" icons, it should not pass `iconRtlMode = IconRtlMode.Mirrored`.

Either way, we should check the results when running an app with a device in rtl.

_Originally posted by @luizgrp in https://github.com/google/horologist/pull/1795#discussion_r1387722572_

**Comment by yschimke** [comment]
Testing here https://github.com/google/horologist/pull/1801

**Comment by luizgrp** [comment]
Related: https://github.com/google/horologist/issues/1803
