### ISSUE TITLE
Review ToggleChip auto mirrored param for Switch

### ISSUE THREAD

**Issue by luizgrp** [google/horologist#1803]
Review if code below can be removed as it seems to have been addressed in https://android-review.git.corp.google.com/c/platform/frameworks/support/+/2651546:

https://github.com/google/horologist/blob/879118c2d83f1016261c2cdb0b70b8d4282ed007/compose-material/src/main/java/com/google/android/horologist/compose/material/ToggleChip.kt#L100-L102

**Comment by yschimke** [comment]
Fixed in https://github.com/google/horologist/pull/2340
