### ISSUE TITLE
[Play Store] Unable to publish apps on Play Store using Horologist

### ISSUE THREAD

**Issue by Fra078** [google/horologist#1830]
Play Console requires compileSdk to be less or equal than 33 for Wear apps but horologist libs are using compileSdk = 34, so every apk using horologist can't be published

**Comment by luizgrp** [comment]
Do you mean Play requires [target sdk](https://developer.android.com/docs/quality-guidelines/wear-app-quality#target-sdk-version) to be between 30 and 33?

If so, then it shouldn't be a problem that Horologist is using compileSdk = 34. 

What's the error message you are seeing when trying to publish?
