### ISSUE TITLE
[Feature Request] Let rotaryWithScroll support nested scrolling

### ISSUE THREAD

**Issue by ichenhe** [google/horologist#1862]
Horologist Version: 0.4.17 

Currently `Modifier.rotaryWithScroll()` takes and  manipulates `ScrollableState` directly, which may bypass the nested scroll mechanism.

Maybe this modifier factory function can take `NestedScrollDispatcher` as another parameter so that it can incorporate nested scrolling. Alternatively, it would be great to have another, more concise API design.

**Comment by yschimke** [comment]
Cc @Kpeved in case you have thoughts

**Comment by ichenhe** [comment]
@Kpeved  Here's my basic idea:

To support nested scrolling, we must implement the following:

- Know the scrolling axis that can not be infered from the `ScrollableState`.
- Have a `NestedScrollDispatcher` to dispatch the event.

**Parameter**

A parameter can be introduced to allow developer to specify the scroll axis and to provide their own `NestedScrollDispatcher` if needed.

<details>
<summary>Example</summary>

```kotlin
data class NestedScrollOptions (
    val axis: NestedScrollAxis,
    val dispatcher: NestedScrollDispatcher = NestedScrollDispatcher()
)

// public api
public fun Modifier.rotaryWithScroll(
    scrollableState: ScrollableState,
    nestedScrollOptions: NestedScrollOptions? = null,
    // others...
)
```

</details>

**Dispatch**

1. Make `RotaryInputNode` extend `DelegatingNode` and register a delegate node: `nestedScrollModifierNode()`. The `NestedScrollConnection` here is meaningless so an empty implementation can be used.
    <details>
    <summary>Example</summary>

    ```kotlin
    private class RotaryInputNode(
      var rotaryScrollHandler: RotaryScrollHandler,
      var nestedScrollDispatcher: NestedScrollDispatcher,
    ) : RotaryInputModifierNode, DelegatingNode() {
      init {
          val conn = object : NestedScrollConnection {}
          delegate(nestedScrollModifierNode(conn, dispatcher = nestedScrollDispatcher))
      }
    }
    ```

    </details>
2. Modify the `RotaryScrollBehavior` to dispatch nested scroll event.
    <details>
    <summary>Example</summary>

    ```kotlin
     // RotaryScrollBehavior
    suspend fun handleEvent(targetValue: Float) {
        scrollAnimation.animateTo() {
            var consumed = dispatcher.dispatchPreScroll(Offset(0f, delta), NestedScrollSource.Wheel).y
            consumed += scrollBy(delta - consumed)
            dispatcher.dispatchPostScroll(
                Offset(0f, consumed),
                Offset(0f, delta - consumed),
                NestedScrollSource.Wheel
            )
        }
    }
    ```

    </details>

**Comment by Kpeved** [comment]
@ichenhe thanks for your feedback and proposal. That request makes total sense. We're working on bringing rotary support by default to Compose for WearOS in AndroidX, so this will be very useful. 
What we have to do is to align this api with similar apis regarding nested scroll support.

**Comment by yschimke** [comment]
This is no longer relevant for the deprecated methods in horologist.
