### ISSUE TITLE
Media sample - address kapt warning

### ISSUE THREAD

**Issue by luizgrp** [google/horologist#1879]
```
> Task :media:sample:hiltJavaCompileDebug
warning: Kapt support in Moshi Kotlin Code Gen is deprecated and will be removed in 2.0. Please migrate to KSP. https://github.com/square/moshi#codegen
1 warning
```

**Comment by yschimke** [comment]
I think it's a false warning. I doubt you are using kapt.

**Comment by yschimke** [comment]
See https://github.com/square/moshi/discussions/1752

**Comment by luizgrp** [comment]
ok, so this ticket would be to:
- assess options listed in https://github.com/google/dagger/issues/4116#issuecomment-1800158406 and address
- remove unused dep https://github.com/google/horologist/blob/85d1f01f02d007a8b93afe81498b39bb1b11a0d2/gradle/libs.versions.toml#L207

**Comment by yschimke** [comment]
Going to close as not our problem
