### ISSUE TITLE
Currency Picker

### ISSUE THREAD

**Issue by yschimke** [google/horologist#190]
Implement a picker for Currency amounts.

See https://github.com/google/horologist/blob/d6a12251b19cfce2d7d0a7c48c18caf02d1120c5/composables/src/main/java/com/google/android/horologist/composables/DatePicker.kt for a template of the approach.

**Comment by MohitMandalia** [comment]
Hi @yschimke want to work on this , could you let me know how should this picker look do you want just currency like USD or with a flag. how do you see this implemented?

**Comment by yschimke** [comment]
Hi, we are just discussing this internally.

Also linking to this issue https://issuetracker.google.com/issues/208843520

**Comment by MohitMandalia** [comment]
Sure let me know how the discussion goes 😊.

**Comment by yschimke** [comment]
This is now possible with https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:wear/compose/compose-material/src/commonMain/kotlin/androidx/wear/compose/material/PickerGroup.kt?q=PickerGroup

But without a spec, closing as out of scope.
