### ISSUE TITLE
Improve result for app helper functions that require capability

### ISSUE THREAD

**Issue by luizgrp** [google/horologist#1901]
### WHAT

For functions that require the own app installed on the wear/phone device (e.g. https://github.com/google/horologist/issues/1900), improve the API to return an explicit result that the app installation/capability is missing. 

### WHY

In order to fail fast instead of timing out.

### HOW

- Assess the possibility.
- Design the API.

**Comment by luizgrp** [comment]
@yschimke checking for capability would require a call to [CapabilityClient.getAllCapabilities](https://developers.google.com/android/reference/com/google/android/gms/wearable/CapabilityClient#getAllCapabilities(int)) which takes time. This would be a "penalty" for calls to a node that already have the capability.

An option would be to add overloaded functions that accept an [AppHelperNodeStatus](https://github.com/google/horologist/blob/c20dd2bfa77bdfb6285463c65e6f6b9c24fc4f82/datalayer/core/src/main/java/com/google/android/horologist/data/apphelper/AppHelperNodeStatus.kt#L25-L30) as a parameter, instead of a node id as a string. Thus the function can check if `AppHelperNodeStatus` has the capability. But the existing functions would remain with the same issue.

Did you have anything different in your mind when suggesting this improvement?

**Comment by yschimke** [comment]
Where was the original comment?

**Comment by luizgrp** [comment]
I'm afraid I can't find it

**Comment by yschimke** [comment]
Your call, you know these APIs better than I do. Feel free to close if you think it's fine.

I think in general fast failure is better, but not sure if it's that simple.

**Comment by luizgrp** [comment]
Closing as per discussion above, but https://github.com/google/horologist/issues/1900 will hopefully help with documentation and samples.
