### ISSUE TITLE
Observable TimePicker state without onTimeConfirm press

### ISSUE THREAD

**Issue by cjrcodes** [google/horologist#1931]
Add the ability to get the current value of TimePicker without having to click the confirm button and having to using onTimeConfirm to get the new value

Example use case: Using TimePicker as a timer only using the hours and minutes, I want to dynamically update a projected time of when the alarm of the timer will sound off, this will be reflected via a Text composable

Time: 12:00 PM
TimePicker: 00:05
Projected time: 12:05 PM

User switches the value on the TimePicker to 01:32, the projected time now reflects this dynamically as the TimePicker state is able to be observed without onTimeConfirm

Time: 12:00 PM
TimePicker: 01:32
Projected time: 01:32 PM

User clicks confirm on the TimePicker and the timer starts

**Comment by yschimke** [comment]
Should we copy the approach of Material3 TimePicker?

https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/material3/material3/src/commonMain/kotlin/androidx/compose/material3/TimePicker.kt;l=606?q=TimePicker

**Comment by yschimke** [comment]
Discussed in context of material3 - as that API isn't changing, closing this.  Consider forking the component if needed.
