### ISSUE TITLE
Revert minSdk from 26 back to 25

### ISSUE THREAD

**Issue by IsakTheHacker** [google/horologist#1968]
This is COMPLETLY INSANE!!! You can't just arbitrarily introduce breaking changes without incrementing the major version let alone even MENTIONING it on the changelog. Please follow semantic versioning like any sane person would do! I don't know why this change was needed in the first place but you need to revert it ASAP since minSdk 25 is the defacto default for Wear OS applications and many people rely on this library.

**Comment by yschimke** [comment]
We should be able to. I'll take a look next week. No offense intended, just assumptions that api 25 devices are rare.

**Comment by yschimke** [comment]
@IsakTheHacker Are you on 0.5.x or 0.4.x?  

As discussed here https://github.com/google/horologist?tab=readme-ov-file#maintained-versions, 0.5.x does have alphas, and so does have breaking changes. I should clarify this more that the development branch will have breaking changes.

I'm not disagreeing about changing back to 25, more flagging that we don't have the same guarantees as Androidx.

**Comment by IsakTheHacker** [comment]
I am on 0.5.x and I guess you're right about horologist not having the same
guarantees as androidx. That makes sense. However I don't think it is okay
to end support left and right just because not many people are running on
such old Android versions. This just seems like a mistake that went through
though so I am looking forward for an eventual fix. And next time, if
breaking changes need to be introduced, please at least mention it in the
changelog so consumers know what to expect from the library. Thank you for
being so helpful and understanding

**Comment by yschimke** [comment]
Will do.

**Comment by yschimke** [comment]
A word of warning, I don't think Androidx shares your agreement on minSdk 25

```
wear/tiles/tiles-renderer/build.gradle

defaultConfig {
    minSdkVersion 26
    
wear/watchface/watchface-complications-data/build.gradle

defaultConfig {
    minSdkVersion 26
```

So this will be best effort, if you find issues at runtime with these libraries, then please let us know.

I'm happy to reduce here, because you'll need these dependencies anyway, which will raise the minSdk but not because of Horologist.

**Comment by IsakTheHacker** [comment]
Could you publish a new release now that this has been fixed?

**Comment by yschimke** [comment]
Yep, will try to get a release this week.

n.b. We will bump the minSdk level for Wear modules to 26 with 0.6.x which isn't yet a thing. So 0.5.x will remain minSdk 25. 

We can't justify or promise to support SDK 25, if bugs get reported, then we likely have to admit it doesn't work. And there is a non zero cost of requiring coreLibraryDesugaring even though it wouldn't be needed on API 26.

See https://github.com/google/horologist/pull/1984
