### ISSUE TITLE
Horologist 0.5.5 and newer breaks multi click buttons

### ISSUE THREAD

**Issue by IsakTheHacker** [google/horologist#1979]
I am trying to solve a bug in my app that has been present since I updated Horologist from 0.5.4 to 0.5.5. My bisecting concluded that:
```
a2262790b277610cc5f950c13823736a8542ba65 is the first bad commit
commit a2262790b277610cc5f950c13823736a8542ba65
Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Date:   Sat Sep 9 07:52:25 2023 +0000

    Bump com.google.android.horologist:horologist-compose-layout
    
    Bumps [com.google.android.horologist:horologist-compose-layout](https://github.com/google/horologist) from 0.5.4 to 0.5.5.
    - [Release notes](https://github.com/google/horologist/releases)
    - [Commits](https://github.com/google/horologist/compare/v0.5.4...v0.5.5)
    
    ---
    updated-dependencies:
    - dependency-name: com.google.android.horologist:horologist-compose-layout
      dependency-type: direct:production
      update-type: version-update:semver-patch
    ...
    
    Signed-off-by: dependabot[bot] <support@github.com>

 wear/build.gradle | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```
which is the dependabot version bump. Downgrading to 0.5.4 on the newest version solved the issue. I am guessing that something changed in 0.5.5 that caused multi click operations to fail.

My MultiClickButton that doesn't work anymore looks like this:
```kotlin
@OptIn(ExperimentalFoundationApi::class)
@Composable
internal fun MultiClickButton(
	onClick: () -> Unit,
	modifier: Modifier = Modifier,
	onLongClick: (() -> Unit)? = null,
	onDoubleClick: (() -> Unit)? = null,
	enabled: Boolean = true,
	colors: ButtonColors = ButtonDefaults.primaryButtonColors(),
	interactionSource: MutableInteractionSource = remember { MutableInteractionSource() },
	shape: Shape = CircleShape,
	border: ButtonBorder = ButtonDefaults.buttonBorder(),
	content: @Composable BoxScope.() -> Unit,
) {
	Button(
		onClick = {},
		modifier = modifier
			.combinedClickable(
				interactionSource = interactionSource,
				indication = null,		//We already get the visual indication by using the standard Material Button
				enabled = enabled,
				onClick = onClick,
				onLongClick = onLongClick,
				onDoubleClick = onDoubleClick,
			),
		enabled = enabled,
		colors = colors,
		interactionSource = interactionSource,
		shape = shape,
		border = border,
		content = content,
	)
}
```

With the update, the button doesn't register ANY types of clicks. Not even normal single clicks.

**Comment by yschimke** [comment]
It looks like this is the Wear Material standard Button. You aren't using a horologist component here?

If so, is it possible that it's just pulling in a newer Wear Material alpha?

**Comment by yschimke** [comment]
If you can make a basic repro, it would help us confirm the issue.  Even one self contained file with an activity and including combinedClickable. We can test against different horologist and compose versions.

**Comment by luizgrp** [comment]
Worth checking this https://github.com/google/horologist/issues/1822#issuecomment-1880827920 while investigating this.

**Comment by yschimke** [comment]
0.5.4 -> 0.5.5 would have picked up this change which looks likely

https://android-review.git.corp.google.com/c/platform/frameworks/support/+/2697934

**Comment by yschimke** [comment]
Closing in favour of https://github.com/google/horologist/issues/1822#issuecomment-1880827920

**Comment by IsakTheHacker** [comment]
Yes you are right that the composable doesn't use any horologist APIs. Is it possible to force horologist to pull in an older version of the dependency before the change that broke this usecase, in build.gradle perhaps?

**Comment by yschimke** [comment]
Technically you can, but that sounds like a bad idea, you might get runtime exceptions.

I'd suggest focusing on the other ticket, we can prototype ways to get combinedClickable working for Wear Compose buttons.

**Comment by yschimke** [comment]
You always have the option to fork the bits you need, I know it's not ideal. But we can't support older versions.  Sorry!

**Comment by IsakTheHacker** [comment]
Okay, understand but it seems like the easiest way to solve this issue right now while staying on the newest version of horologist. Do you know which dependency it is that I need to downgrade manually in Gradle (the one that caused this bug)?
