### ISSUE TITLE
rotaryWithScroll not working with ScalingLazyColumn

### ISSUE THREAD

**Issue by AdrianDev0** [google/horologist#2008]
Hi, I created a very basic sample with a `ScalingLazyColumn` using `rotaryWithScroll` to be able to scroll via the crown/RSB. But if I rotate the RSB, the list isn't scrolling. I also tried it with `onRotaryScrollEvent` which is suggested [here](https://developer.android.com/training/wearables/compose/rotary-input#scroll) which works.
So is it intended to use the old `onRotaryScrollEvent` or is `rotaryWithScroll` with `ScalingLazyColumn` just not working correctly? Or am I doing sth. wrong here?

Used on Pixel Watch with Wear OS 4 and Horologist 0.5.14

```
@OptIn(ExperimentalHorologistApi::class)
@Composable
fun WearApp() {
    MyApplicationTheme {

        val scrollState = rememberScalingLazyListState()
        val focusRequester = rememberActiveFocusRequester()
        LaunchedEffect(Unit) {
            focusRequester.requestFocus()
        }

        ScalingLazyColumn(
            modifier = Modifier
                .fillMaxWidth()
                .rotaryWithScroll(
                    focusRequester = focusRequester,
                    scrollableState = scrollState,
                ),
        ) {
            items(List(100) {i -> "$i"}) {
                Box(modifier = Modifier
                    .fillMaxWidth()
                    .height(50.dp),) {
                    Text(text = it)
                }
            }
        }
    }
}
```

**Comment by yschimke** [comment]
You need to pass the scrollState into the ScalingLazyColumn.

Also you don't need the LaunchedEffect.  rememberActiveFocusRequester is enough.
