### ISSUE TITLE
Detect if audio offload support Opus

### ISSUE THREAD

**Issue by Tolriq** [google/horologist#2033]
I'm trying to check in Media3 and horologist code but I can't find a way to detect if a watch support Opus offload or not? (Android doc says that Android 11+ may support it, not that it's mandatory)

Use case would be to transcode large media for caching on the watch either in mp3 or opus depending on the watch capabilities.

**Comment by yschimke** [comment]
It should be supported on Android universally since Android 5.0 https://source.android.com/docs/compatibility/5.0/android-5.0-cdd#5_1_1_audio_codecs

And for Wear 4 (Android 13) https://source.android.com/docs/compatibility/13/android-13-cdd#51_media_codecs

These apply to android devices including Wear.

> If device implementations declare support for the android.hardware.audio.output feature, they must support decoding the following audio formats:
> [C-1-10] Opus

**Comment by yschimke** [comment]
Looks like you can check with MediaCodecList example https://stackoverflow.com/questions/11791473/get-supported-codec-for-android-device

**Comment by Tolriq** [comment]
I'm talking about offload capabilities to reduce battery usage not just the codec usage. Horologist support it but does not directly expose a way to check for the supported cases.

Offload is API29 and Opus is a possible one after API 31, in both case they are not mandatory.

https://source.android.com/docs/compatibility/13/android-13-cdd#554_audio_offload

Anyway I crossposted in media3 and they have a class for that https://github.com/androidx/media/issues/1093

https://github.com/androidx/media/blob/release/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/audio/DefaultAudioOffloadSupportProvider.java

**Comment by yschimke** [comment]
Sorry, I must be tired :)

Thanks for linking here.
