### ISSUE TITLE
Tiles Previews inside Android Studio

### ISSUE THREAD

**Issue by yschimke** [google/horologist#205]
See https://github.com/android/wear-os-samples/pull/399

![image](https://user-images.githubusercontent.com/231923/172150236-5b6e7b5e-b152-4a16-9f5e-fa6a9c9eeae4.png)

cc @ataulm

**Comment by ataulm** [comment]
<img width="790" alt="image" src="https://user-images.githubusercontent.com/2678555/172168914-bed61056-01c3-4c6e-875f-ec56f3931678.png">

Are these ones misaligned due to bugs in the renderer or is this what it looks like on the emulator too?

**Comment by yschimke** [comment]
The layout isn't designed to handle variable number of items, Probably a good follow up to make sure it supports that cleanly.  Although moving to Tiles Material could fix that for little effort.

It should look same on emulator, but previews make it easy to reach states that might be hard in the app.

**Comment by yschimke** [comment]
https://github.com/google/horologist/pull/218
