### ISSUE TITLE
Compose-Layout transitive dep on compose-navigation

### ISSUE THREAD

**Issue by Tolriq** [google/horologist#2061]
I'm not using compose navigation in my apps but a custom solution based on Voyager.

Compose-layout currently have a transitive dependency on compose-navigation that is only used for a link in the javadoc of `AppScaffold`.

Would it be possible to remove that unnecessary dependency in a future release?

**Comment by yschimke** [comment]
Fixed in next release

**Comment by Tolriq** [comment]
Thanks. I guess asking for media-ui-navigation split would be too much to ask.

**Comment by yschimke** [comment]
Can you raise it with a separate issue, it's probably doable, I'd like to confirm with another internal team that uses some of this.  It looks like MediaNavController, NavigationScreens, PlayerLibraryPagerScreen, MediaPlayerScaffold.

**Comment by Tolriq** [comment]
I'm not far enough in the project to exactly know what I'll use from that part of horologist.

But will do if I decide to use the full ui package. Thanks for the follow up.
