### ISSUE TITLE
Improve tracking Tile installation

### ISSUE THREAD

**Issue by luizgrp** [google/horologist#2066]
Since [getActiveTilesAsync](https://developer.android.com/reference/androidx/wear/tiles/TileService#getActiveTilesAsync(android.content.Context,java.util.concurrent.Executor)) became available, our guidance should be updated to use it, instead of using the information provided by [onTileAddEvent](https://developer.android.com/reference/androidx/wear/tiles/TileService#onTileAddEvent(androidx.wear.tiles.EventBuilders.TileAddEvent)) and [onTileRemoveEvent](https://developer.android.com/reference/androidx/wear/tiles/TileService#onTileRemoveEvent(androidx.wear.tiles.EventBuilders.TileRemoveEvent)).

---

Suggestion:

1) Remove `markTileAsInstalled` and `markTileAsRemoved` functions;
2) Add function to update the tracking of installed tiles:

```kotlin
    public suspend fun updateInstalledTiles() {
        val activeTiles = TileService.getActiveTilesAsync(context, executor).await()

        surfacesInfoDataStore.updateData { info ->
            info.copy {
                tiles.clear()
                for (activeTileIdentifier in activeTiles) {
                    tiles.add(tileInfo {
                        timestamp = System.currentTimeMillis().toProtoTimestamp()
                        name = activeTileIdentifier.componentName.className
                    })
                }
            }
        }
    }
```
3) Update guidance in https://google.github.io/horologist/datalayer-helpers-guide/ to call `updateInstalledTiles` in `onTileAddEvent` and `onTileRemoveEvent`.

**Comment by luizgrp** [comment]
@yschimke @garanj please review.

**Comment by garanj** [comment]
Looks good!!

**Comment by oas004** [comment]
@luizgrp Can I try to pick this up? :) Would it be nice to deprecate the `markTileAsInstalled` and `markTileAsRemoved` or is it okay to just remove them? :)

**Comment by luizgrp** [comment]
@oas004 yes, please!
Let's deprecate them until next major release 👍 

Please let me know if the sample apps are enough to test this functionality or if they need any improvement.

**Comment by luizgrp** [comment]
Good call 👍 https://github.com/google/horologist/issues/2443

We have been making a new major release for every minor release of Wear Compose.
