### ISSUE TITLE
Review pipeline initializations

### ISSUE THREAD

**Issue by luizgrp** [google/horologist#2080]
The answer seems to be in [DAC](https://developer.android.com/topic/architecture/ui-layer/state-production#initializing-state-production):

> Flow APIs allow for this with the [started](https://developer.android.com/topic/architecture/ui-layer/31) argument in the [stateIn](https://developer.android.com/topic/architecture/ui-layer/17) method. 

Which seems to be what NiA is using.

Then it continues:

> In the cases where this is inapplicable, define an [idempotent](https://en.wikipedia.org/wiki/Idempotence) initialize() function to explicitly start the state production pipeline as shown in the following snippet:

So we should re-evaluate our cases and see when the stateIn + started WhileSubscribed is applicable.

_Originally posted by @luizgrp in https://github.com/google/horologist/pull/2078#discussion_r1507814208_

**Comment by yschimke** [comment]
Closing as low priority, reopen if working on this.
