### ISSUE TITLE
[Feature request] scalingLazyColumnDefaults does not support userScrollEnabled parameter

### ISSUE THREAD

**Issue by Digipom** [google/horologist#2087]
Please add userScrollEnabled to ScalingLazyColumnDefaults.scalingLazyColumnDefaults(...)

**Comment by yschimke** [comment]
Adding in here. https://github.com/google/horologist/pull/2088

I was tempted to mark this method as deprecated. But if you want to use the default ScalingLazyColumn API and also AppScaffold/ScreenScaffold then it's still useful.

Generally we want to encourage use or `rememberResponsiveColumnState(padding)` as it should give a better result across devices and content variants.

**Comment by Digipom** [comment]
I just migrated from Horologist 0.5.6 to 0.5.22 so I also migrated from WearNavScaffold / scrollable to AppScaffold / SwipeDismissableNavHost / composable with columnState.

I'm still using scalingLazyColumnDefaults in two places:

1) My media player:
val columnState = rememberColumnState(
                        factory = ScalingLazyColumnDefaults.scalingLazyColumnDefaults(
                            initialCenterIndex = 0
                        )
                    )
2) The main screen:
ScalingLazyColumnDefaults.scalingLazyColumnDefaults(
                                autoCentering = AutoCenteringParams(itemIndex = 0),
                                initialCenterIndex = 0,
                                userScrollEnabled = shouldUserScrollBeEnabled,
                            )

Is the responsive layout able to replicate this behavior?

0.5.22 doesn't seem to have a "rememberResponsiveColumnState" but rememberColumnState takes a factory that defaults to ScalingLazyColumnDefaults.responsive().

**Comment by yschimke** [comment]
0.5.23 has this API. We got internal guidance that we should adjust the padding based on the content.

See here for an example

https://github.com/android/wear-os-samples/blob/main/ComposeStarter/app/src/main/java/com/example/android/wearable/composestarter/presentation/MainActivity.kt#L136

You can see a diff here using it https://github.com/android/wear-os-samples/pull/1020/files including screenshots

**Comment by Digipom** [comment]
@yschimke I tried it and it no longer centers the contents. 

i.e.:
val columnState = rememberColumnState(
                        factory = ScalingLazyColumnDefaults.scalingLazyColumnDefaults(
                            initialCenterIndex = 0
                        )
                    )
vs
val columnState = rememberResponsiveColumnState()

![image](https://github.com/google/horologist/assets/2005192/d6475c04-df9d-46aa-af09-2eb2f56f0004)![image](https://github.com/google/horologist/assets/2005192/1391c6bd-c63e-4c6b-829d-d9a5e0c38619)

I tried adjusting verticalAlignment and contentPadding but to no avail. Should I just stay with scalingLazyColumnDefaults for now? If this behavior is not possible with the new APIs, then I would request to please not deprecate the old ones. Thank you.

**Comment by yschimke** [comment]
OK, I'll leave this API. That's basically by design.

So stick with the API you are using.

**Comment by Digipom** [comment]
I also noticed another regression where you can no longer scroll items to the centre of the screen on some lists; I have to investigate this one further.

**Comment by Digipom** [comment]
@yschimke Just for more clarity, what am I missing by not using the rememberResponsiveColumnState() or rememberColumnState() that uses a responsive factory by default? I know the library is in active development but all of the different options are a little overwhelming. Thank you.

**Comment by Digipom** [comment]
@yschimke Thanks, this helps a lot. Just as a reference, here's what I see as the bottom-most scroll position with the different options:

1) Using the now-deprecated `scrollable()`:
<img width="205" alt="image" src="https://github.com/google/horologist/assets/2005192/6c46cd75-5965-48eb-aa82-99158ac59088"><img width="205" alt="image" src="https://github.com/google/horologist/assets/2005192/68e2d538-340f-492c-8e2d-5fc9219979de">

This can still be achieved by using `val columnState = rememberColumnState(factory = ScalingLazyColumnDefaults.scalingLazyColumnDefaults())` in 0.5.22.

2) `rememberColumnState(factory = ScalingLazyColumnDefaults.belowTimeText())`

<img width="205" alt="image" src="https://github.com/google/horologist/assets/2005192/580ac688-86ad-496f-948e-e0fc37933d49"><img width="205" alt="image" src="https://github.com/google/horologist/assets/2005192/f2bf11bf-f082-4bfa-9a03-98a5a2a17193">

3) val columnState = rememberColumnState()
<img width="205" alt="image" src="https://github.com/google/horologist/assets/2005192/11d6f19f-49fd-4db5-bf85-8b478b4ad103">
<img width="205" alt="image" src="https://github.com/google/horologist/assets/2005192/780904b7-e314-4731-9928-809cf241dec6">

4) `val columnState = rememberResponsiveColumnState()`
<img width="205" alt="image" src="https://github.com/google/horologist/assets/2005192/967afa34-df05-404f-bf51-464104f50543">
<img width="205" alt="image" src="https://github.com/google/horologist/assets/2005192/dc11b4e2-8697-4795-8165-4a09ac0c646e">

To me, the terminal state of the square scroll does look like a bug but if we can still use `val columnState = rememberColumnState(factory = ScalingLazyColumnDefaults.scalingLazyColumnDefaults())` then that's fine.

For rejections due to clipping, we had them due to Dialog behavior on round devices: https://issuetracker.google.com/issues/310112608

Thanks again for the details, it's much clearer for us now.

**Comment by yschimke** [comment]
If you want square devices, then you probably want to control everything. A lot of these changes are only with round devices in mind.

So I'll keep that API for you. Hopefully everything else works automatically like RSB even if you control layout manually
