### ISSUE TITLE
Improve Tile tracking initialization

### ISSUE THREAD

**Issue by kul3r4** [google/horologist#2146]
At the moment we require the watch app at least to start once after code is updated in order to be able to track tile install status. 
Suggestion from @yschimke in https://github.com/google/horologist/pull/2143#discussion_r1529884767 is to avoid asking apps to do this instead having a RPC call to refresh that data.

**Comment by yschimke** [comment]
Mostly a dupe of https://github.com/google/horologist/issues/2066
