### ISSUE TITLE
Add Id to ImageResource mapper

### ISSUE THREAD

**Issue by ataulm** [google/horologist#229]
```kotlin
fun idToImageResource(id: Int) = ImageResource.Builder()
       .setAndroidResourceByResId(
               AndroidImageResourceByResId.Builder()
                       .setResourceId(id)
                       .build()
       )
       .build()
```

From here:

https://github.com/joreilly/PeopleInSpace/pull/139/files#diff-4058974ed1ff8fbb817967ab294ee5a8b422543b015c50cf3481cc2fddffbe0cR119-R126

I'm using it for a component audit (in combination with `LayoutPreview`) but presumably it's handy for the tile renderer too.

Notes:

- consider adding `@DrawableRes` to the function

**Comment by ataulm** [comment]
I misread the function, but it's still useful to add (my notes are less useful 😂 )

**Comment by yschimke** [comment]
+1 to DrawableRes.  Also as an extension function on Resources.Builder, it should show up magically inside the Preview blocks and so on.
