### ISSUE TITLE
Cannot override color for ResponsiveListHeader

### ISSUE THREAD

**Issue by kul3r4** [google/horologist#2319]
Setting the contentColor to white does not override the color of the ResponsiveListHeader, see snapshot from emulator 
<img width="541" alt="Screenshot 2024-07-30 at 1 55 45 PM" src="https://github.com/user-attachments/assets/aaba9146-dc9c-4827-b2c1-c5f6756be8e8">
code to reproduce is checked in https://github.com/android/wear-os-samples/compare/main...kul3r4:wear-os-samples:white-header?expand=1#diff-901c6e532a23554e690786bb4ff8779fa15b9ea09201c70e32efe48b0bf5d166R167

**Comment by yschimke** [comment]
I believe this is caused by a bad assumption about the order of LocalTextStyle and LocalContentColor.

We could do a fix, make sure that ResponsiveListHeader sets color through text style if set.

**Comment by yschimke** [comment]
I lied.  It was scaling

![image](https://github.com/user-attachments/assets/bcf35543-1dee-4a02-be9d-c4b21fe94d1d)

![image](https://github.com/user-attachments/assets/60ad7de6-f195-43c3-9bc8-cab62d50d1bf)

Ignore "Dialog padding" I'm reusing an existing screenshot to explain.

**Comment by kul3r4** [comment]
Tried increasing the padding setting the first item as a Card, I am still getting the scaling edge effect 
![Screenshot_20240805_132139](https://github.com/user-attachments/assets/cd81994c-2d52-4f33-83db-17a0f69fd90b)

For comparison, this is when it's text
![Screenshot_20240805_132241](https://github.com/user-attachments/assets/190d939b-e4a5-4d85-a060-f730caad2de6)

**Comment by kul3r4** [comment]
It applies to the first item independently of the padding
![Screenshot_20240805_132902](https://github.com/user-attachments/assets/1ac533e6-3b7e-40ee-9315-fd85e6415c5a)

**Comment by yschimke** [comment]
Try with the sample I sent in chat. It shows the scaling for the first item

**Comment by kul3r4** [comment]
<img width="1310" alt="Screenshot 2024-08-05 at 2 48 24 PM" src="https://github.com/user-attachments/assets/b171226b-b199-4ff4-9c54-041088e7e898">

**Comment by yschimke** [comment]
OK, back from holidays.  This test shows what I mean https://github.com/google/horologist/pull/2338

**Comment by yschimke** [comment]
No fix planned. 

Apps that are ok with some title scaling should choose ItemType.Text (16%) and if not ItemType.BodyText (21%)
