### ISSUE TITLE
Add support for WEBP or PNG with transparency to Tiles image helpers

### ISSUE THREAD

**Issue by yschimke** [google/horologist#251]
The current conversion code for bitmaps and canvas elements to Tile ImageResources, uses RGB_565.

https://github.com/google/horologist/blob/40801e6e64b55b7e0caeaba96151e8577f399afc/tiles/src/main/java/com/google/android/horologist/tiles/images/images.kt#L69

This is safe format, but requires extra work and also does not support alpha channel.

We should add a flag to support other formats including png, webp.

This probably involves removing hard coded format when flag is set

```
setFormat(ResourceBuilders.IMAGE_FORMAT_RGB_565)
```

and use, or other conversion code.

```
    val bytes = ByteArrayOutputStream().apply {
        compress(Bitmap.CompressFormat.PNG, 100, this)
    }.toByteArray()
```

We can assume Coil for our conversion code if it helps, and to start with avoiding conversions, but to be confirmed.

A later change might be also this code path https://github.com/google/horologist/blob/2f15272f92291bcdbdacd66b1042e42802c45cb7/tiles/src/main/java/com/google/android/horologist/tiles/canvas/canvas.kt

**Comment by yschimke** [comment]
cc @ataulm

**Comment by yschimke** [comment]
We should make this a flag, useRgb565? 

Current logic when useRgb565.

When not useRgb565, remove setFormat, and pass through the existing bytes. Tile rendering should ask the system to decode.

Samples should show a png, webp or jpg working without conversion.

**Comment by ataulm** [comment]
I think for a "good first issue" this needs more context:

- what's the problem and which APIs does this affect currently?
- Are we talking only [about this function](https://github.com/google/horologist/blob/40801e6e64b55b7e0caeaba96151e8577f399afc/tiles/src/main/java/com/google/android/horologist/tiles/images/images.kt#L85)? Or will further changes need to be made elsewhere?
- is this something that we can do without exposing a flag/new API? e.g. detect the type of the image and convert it with the correct compression?
- are there similar APIs in well-established libraries like Coil, Glide and Picasso that we should follow?

**Comment by yschimke** [comment]
Yep, I'll update later today.  Thanks for flagging @ataulm

**Comment by Tolriq** [comment]
Sorry I missed that original issue.

The `toImageResource` function itself is agnostic of the image downloader.
Being able to keep the alpha channel is important if you apply transformations like CircleCrop.

I would just pass an argument with default value Bitmap.Config.RGB_565 allowing users to pass Bitmap.Config.ARGB_8888 when needed.

Changing to Bitmap.Config.ARGB_8888 and `.setFormat(ResourceBuilders.IMAGE_FORMAT_ARGB_8888)` properly keep the alpha channel.

I can make a PR once the API surface is decided (because I guess the proto layout part may not support all different Android version BitmapConfig so it may require to only support 565 and 8888 or whatever is best)

**Comment by yschimke** [comment]
@castedmo What formats can be assumed to be supported in Tiles?

```
enum ImageFormat {
  // An undefined image format.
  IMAGE_FORMAT_UNDEFINED = 0;

  // An image format where each pixel is stored on 2 bytes, with red using 5
  // bits, green using 6 bits and blue using 5 bits of precision.
  IMAGE_FORMAT_RGB_565 = 1;

  // An image format where each pixel is stored on 4 bytes.
  // RGB and alpha (for translucency) is stored with 8 bits of precision.
  IMAGE_FORMAT_ARGB_8888 = 2;
}
```

If I remember right, these two obviously.  But UNDEFINED actually means whatever the platform can handle?

**Comment by castedmo** [comment]
Only [those two](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:wear/protolayout/protolayout-renderer/src/main/java/androidx/wear/protolayout/renderer/inflater/DefaultInlineImageResourceResolver.java;l=70-81;drc=f8ef094f84fdec434e3df1a6447bf58f31ee4135;bpv=0;bpt=0) are supported. UNDEFINED Is just the default value for when it's unset.
