### ISSUE TITLE
Make PlayerRepository getSeekBackIncrement nullable

### ISSUE THREAD

**Issue by yschimke** [google/horologist#308]
See https://github.com/google/horologist/pull/307#discussion_r912049828

**Comment by MohitMandalia** [comment]
Hi @yschimke so as far as I understood we need to make this getSeekBackIncrement nullable and return unknown or null instead.

**Comment by yschimke** [comment]
Hey, we discussed this one and decided a previous PR addressed this already, and didn't want further changes.

I'll review some existing PRs and tagged some for first time contributors. Give me the weekend.

**Comment by MohitMandalia** [comment]
Sure thank you @yschimke

**Comment by yschimke** [comment]
@MohitMandalia labelled some here https://github.com/google/horologist/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

**Comment by MohitMandalia** [comment]
Thank you 😄
