### ISSUE TITLE
StandardChip placeholder icon color not changing when disabled

### ISSUE THREAD

**Issue by luizgrp** [google/horologist#329]
[StandardChip](https://github.com/google/horologist/blob/c5fb2c1461dd04ecf1c4aba27d00a50cd8be6441/media-ui/src/main/java/com/google/android/horologist/media/ui/components/base/StandardChip.kt) **placeholder** icon should have an alpha applied in order to change the color when on disabled state.

Compare:

![Screen Shot 2022-07-11 at 15 17 40](https://user-images.githubusercontent.com/878134/178320582-738706be-9d98-4fca-a024-6d2daea85a33.png)

Our [implementation](https://github.com/google/horologist/blob/63d4d99cfdee41cf531bc3677d15c9a9705fff2c/media-ui/src/main/java/com/google/android/horologist/media/ui/components/base/SecondaryChip.kt#L109) relies on [Chip](https://github.com/androidx/androidx/blob/9818b6f43b810feca64120b790df7204f0399150/wear/compose/compose-material/src/commonMain/kotlin/androidx/wear/compose/material/Chip.kt) from `androidx.wear.compose.material` which seems to [implement](https://github.com/androidx/androidx/blob/9818b6f43b810feca64120b790df7204f0399150/wear/compose/compose-material/src/commonMain/kotlin/androidx/wear/compose/material/Chip.kt#L226-L227) this functionality. From the [kdoc](https://github.com/androidx/androidx/blob/9818b6f43b810feca64120b790df7204f0399150/wear/compose/compose-material/src/commonMain/kotlin/androidx/wear/compose/material/Chip.kt#L181-L183):

> In order to correctly render when the Chip is not enabled the icon must set its alpha value to [LocalContentAlpha].

However, our [implementation](https://github.com/google/horologist/blob/c5fb2c1461dd04ecf1c4aba27d00a50cd8be6441/media-ui/src/main/java/com/google/android/horologist/media/ui/components/base/StandardChip.kt#L106-L108) uses Coil's [rememberAsyncImagePainter](https://github.com/coil-kt/coil/blob/70300e5909a561d7e1026c660b8f28be3f0051a6/coil-compose-singleton/src/main/java/coil/compose/SingletonAsyncImagePainter.kt#L45-L47) to display a placeholder, which receives a `Painter` type as placeholder, and might not work well with that alpha applied in Chip.

#### Expected outcome from this task

- PrimaryChip preview for disabled state displays placeholder icon with correct alpha applied
- SecondaryChip preview for disabled state displays placeholder icon with correct alpha applied
- Other previews for PrimaryChip and SecondaryChip are not affected
- PrimaryChip snapshot test for disabled state displays placeholder icon with correct alpha applied
- SecondaryChip snapshot test for disabled state displays placeholder icon with correct alpha applied
- Other snapshot tests for PrimaryChip and SecondaryChip are not affected

**Comment by MohitMandalia** [comment]
This might already be resolved please confirm I can see icon with correct alpha , please confirm

<img width="399" alt="Screenshot 2022-07-10 at 7 00 30 PM" src="https://user-images.githubusercontent.com/36087806/178147200-4a2e0a8e-7ec0-4cef-9ce8-10e6cb0726cd.png">

**Comment by luizgrp** [comment]
@MohitMandalia thanks for checking this, it looks like the issue happens with the **placeholder** icon. I've updated the issue title and description.

The issue also happens when an image is used instead of icon, which I will raise a separate issue for it:
|disabled|enabled|
|---|---|
|![Screenshot_20220711_150839](https://user-images.githubusercontent.com/878134/178323910-16bf9f4c-e9d5-46bb-b592-4a2c8388ba3d.png)|![Screenshot_20220711_151339](https://user-images.githubusercontent.com/878134/178323917-f9a7b0c1-5643-498a-bd77-aaa8148322ca.png)|

**Comment by MohitMandalia** [comment]
Okk cool.

**Comment by oas004** [comment]
Hey, I was trying to look into this and I was wondering; is there a reason why you can not just apply a LocalContentAlpha.Current  to the image if it is disabled? :smile:  From the previews it seems correct, but I got thrown off by this
```
However, our implementation uses Coil's rememberAsyncImagePainter to display a placeholder, 
which receives a Painter type as placeholder, and might not work well with that alpha applied in Chip.
```

Does that mean that I would need to deprecate and alter the api to not get a painter as a placeholder? and then use something else than rememberAsyncImagePainter?

With the alpha applied to the images, it looks like this for the placeholder disabled preview

<img width="315" alt="Screenshot 2022-08-29 at 16 49 12" src="https://user-images.githubusercontent.com/54936943/187273790-d2108001-adcf-43cd-b2a6-0fee161cd3f6.png">

**Comment by yschimke** [comment]
@oas004 if you can see it fixed with this, please put up a PR. Thanks!
