### ISSUE TITLE
Implement haptics on scrolling

### ISSUE THREAD

**Issue by luizgrp** [google/horologist#373]
From Josef:

> One thing we should priotise is making sure the haptics are felt when users scroll the RSB to move up / down the screen
> Premium haptics (RSB scroll, real-time events, error staties, etc) are enabled on supported devices
> having premium haptics on scroll is like a P0 for UX

**Comment by yschimke** [comment]
This is on hold for now, Wear Compose 1.1 may include improved haptics support and this isn't possible without frontrunning that support, with somewhat equivalent effort.

**Comment by luizgrp** [comment]
@Kpeved should this ticket be closed? I believe you implemented it
