### ISSUE TITLE
Player screen displays wrong state after launching from ongoing notification

### ISSUE THREAD

**Issue by luizgrp** [google/horologist#419]
Player screen in media sample app displays wrong state for play/pause button after launching it from ongoing notification while a song is playing.

Video:

https://user-images.githubusercontent.com/878134/179998919-3721c582-44d2-4795-8c7d-5d91a67e72e1.mp4

Device: Galaxy Watch4 Classic (4W2J) - SM-R895F

#### Steps to reproduce

1) Launch the app and play a song;
2) Lock screen;
3) Tap on the ongoing notification icon;

#### Expected result

Player screen is displayed in playing state: pause button is displayed, progress is changing, music is still playing in background.

#### Actual result

Player screen is displayed in playing state: progress is changing, music is still playing in background. However, play button is displayed for few seconds until it is switched to pause.

**Comment by yschimke** [comment]
Should be fixed in https://github.com/google/horologist/pull/424
