### ISSUE TITLE
Revert workaround to fix playing songs at specific index

### ISSUE THREAD

**Issue by luizgrp** [google/horologist#496]
After https://github.com/androidx/media/issues/85 gets fixed and media3 dependency is updated in the project, revert changes made in https://github.com/google/horologist/pull/497 that are a workaround for this issue:
- `mediaIndexToSeekTo` and `onTimelineChanged` should be removed;
- calls to `seekTo`, `prepare` and `play` should be made by `setMediaListAndPlay`;

As alternative, function `setMediaListAndPlay` should be removed and a `setMediaList(mediaList, index)` added instead. `setMediaListAndPlay` is taking care of playing at the moment to avoid having clients to code a "delay" call as per in https://github.com/google/horologist/pull/494

**Comment by fstanis** [comment]
As of #646, reverting these two things in `PlayerRepositoryImpl.kt`:

- Remove `private fun updateTimeline`
- Remove `EVENT_TIMELINE_CHANGED` from `eventHandlers`

**Comment by luizgrp** [comment]
https://github.com/androidx/media/issues/85 was fixed in [1.0.0-beta03](https://github.com/androidx/media/issues/85), this can be reverted as we are already [using](https://github.com/google/horologist/blob/f24c424766ae78da8cd069080e325e045855879c/gradle/libs.versions.toml#L7) that version.
