### ISSUE TITLE
TextField for Wearable

### ISSUE THREAD

**Issue by Fra078** [google/horologist#512]
Text fields are not recommended by Google on wearable devices, but sometime apps needs to use them (an example is Log-in in standalone apps) but all the ways on Wear Compose to call keyboard are  uncomfortable to use and are rich of issues. Can you implement a simplified and functional way for text input?

**Comment by yschimke** [comment]
What are you imagining? Say a text field, with visible border to invite a touch.  then launching out to the text entry activities and updating in place?

Similar API to https://developer.android.com/jetpack/compose/text ?

**Comment by Fra078** [comment]
> What are you imagining? Say a text field, with visible border to invite a touch. then launching out to the text entry activities and updating in place?
> 
> Similar API to https://developer.android.com/jetpack/compose/text ?

I was thinking to a Button which opens the keyboard

**Comment by yschimke** [comment]
Are you expecting an actual keyboard implemented in Horologist? I was thinking we would just call out to  `Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH)` or `RemoteInputIntentHelper.createActionRemoteInputIntent()` but maybe I misunderstood?

**Comment by Fra078** [comment]
I know that you can use remote intent helper but using it you can't set a type of allowed content (like only put numbers) or text type(like password)

**Comment by yschimke** [comment]
I don't think a keyboard implementation in library form in Horologist would be appropriate.  There is an established mechanism of Remote Intents, that could be adapted to support alternative keyboard apps. Maybe that would be more appropriate, a way for apps to use the best available installed keyboard app?

Going to close this as we won't be a keyboard app in Horologist.
