### ISSUE TITLE
Rename CoroutinesTileService

### ISSUE THREAD

**Issue by ataulm** [google/horologist#523]
The androidx.watchfaces lib includes `SuspendingComplicationDataSourceService`, so perhaps we should rename `CoroutinesTileService` to `SuspendingTileService` for consistency, if the goal is for it to be promoted into androidx.tiles eventually.

**Comment by ataulm** [comment]
If we make this change, we'd have to update the codelab and code sample. 

Would we keep both for a few versions and deprecate the old name?

**Comment by yschimke** [comment]
@ataulm The change is simple, so I'd just make it without deprecating.

**Comment by yschimke** [comment]
I should have marked it experimental, might be a good time to do that also.

https://github.com/google/horologist/blob/9de4cd176b0a0dda287ac93ef590d42567011bdf/tiles/src/main/java/com/google/android/horologist/tiles/CoroutinesTileService.kt#L42

**Comment by ataulm** [comment]
Do we have guides on what experimental means and when something is no
longer experimental?

**Comment by yschimke** [comment]
No, only common sense, it's a warning.  But we ultimately don't promise it for anything.

This could be a good start https://medium.com/androiddevelopers/jetpack-compose-accompanist-an-faq-b55117b02712, see **Binary Compatibility**.

**Comment by MalekGC** [comment]
Someone should probably update the [code lab](https://developer.android.com/codelabs/wear-tiles), and the [git repo](https://github.com/googlecodelabs/wear-tiles), since they're supposed to have working code to help teach new developers.

**Comment by mrspaceman** [comment]
I'll echo this here as they still dont seem to be updated years after the PR.
Someone should probably update the [code lab](https://developer.android.com/codelabs/wear-tiles), and the [git repo](https://github.com/googlecodelabs/wear-tiles), since they're supposed to have working code to help teach new developers.
