### ISSUE TITLE
Implement download progress indicator for individual media

### ISSUE THREAD

**Issue by luizgrp** [google/horologist#540]
On [PlaylistDownloadScreen](https://github.com/google/horologist/blob/78cc8b29013966f7120df7b422d109480b30b705/media-ui/src/main/java/com/google/android/horologist/media/ui/screens/entity/PlaylistDownloadScreen.kt), implement the download [circular progress indicator](https://developer.android.com/training/wearables/compose/progress-indicator) for individual media items:

<img width="244" alt="Screen Shot 2022-09-01 at 08 44 29" src="https://user-images.githubusercontent.com/878134/187861903-5bef312a-bac2-45b0-a879-bfca419f8a76.png">

The UI model [DownloadMediaUiModel](https://github.com/google/horologist/blob/78cc8b29013966f7120df7b422d109480b30b705/media-ui/src/main/java/com/google/android/horologist/media/ui/state/model/DownloadMediaUiModel.kt#L22) already contains the progress information in field [Downloading.progress](https://github.com/google/horologist/blob/78cc8b29013966f7120df7b422d109480b30b705/media-ui/src/main/java/com/google/android/horologist/media/ui/state/model/DownloadMediaUiModel.kt#L41), and the screen is already displaying the progress label ("68% of 13MB" or "Waiting...").

If `Downloading.progress` is [Waiting](https://github.com/google/horologist/blob/78cc8b29013966f7120df7b422d109480b30b705/media-ui/src/main/java/com/google/android/horologist/media/ui/state/model/DownloadMediaUiModel.kt#L62) then it should display an **indeterminate** circular progress indicator:

<img width="255" alt="Screen Shot 2022-09-01 at 08 49 38" src="https://user-images.githubusercontent.com/878134/187863512-f9b0170d-b899-4afa-a5ed-536ffda8db56.png">

If `Downloading.progress` is [InProgress](https://github.com/google/horologist/blob/78cc8b29013966f7120df7b422d109480b30b705/media-ui/src/main/java/com/google/android/horologist/media/ui/state/model/DownloadMediaUiModel.kt#L64) then it should display a **determinate** circular progress indicator, using the `InProgress.progress` field as value:

<img width="260" alt="Screen Shot 2022-09-01 at 08 49 27" src="https://user-images.githubusercontent.com/878134/187863943-aeb535f3-7206-4fa9-966d-1b095cbd7dbb.png">

`InProgress.progress` is currently defined as String, it would be nice to change it to Float and adapt the code accordingly.

**Comment by luizgrp** [comment]
Adding missing specs:

![Screen Shot 2022-09-12 at 10 22 30](https://user-images.githubusercontent.com/878134/189630542-bb5f842d-b5ab-498c-bebb-cde948da7fd0.png)

![Screen Shot 2022-09-12 at 10 44 29](https://user-images.githubusercontent.com/878134/189630551-04220df1-5443-448c-bb75-8c889fcd84fc.png)

![Screen Shot 2022-09-12 at 11 20 56](https://user-images.githubusercontent.com/878134/189630627-3d5bddeb-3049-46c9-8308-61953e16f50e.png)

**Comment by oas004** [comment]
@luizgrp I was wondering if it would be possible to list out what is left after #567 for this issue to be considered done? :) I remember there was some refactoring that we left out. Furthermore, would it be possible to get a design for the large icon type as well? As I think the one above is only one of the permutations :)

**Comment by luizgrp** [comment]
@oas004 this issue is considered done! the comments left there are minor refactoring suggestions, no need to worry about. But if you are up for it, think about how to remove duplication of code in `StandardChip` and `StandardChipIconWithProgress`.

Regarding the design for large icon, we will only have them once they become part of the requirements, which they are not at the moment. But I will let you know if that changes.

Thanks for bringing it to my attention, closing it now!

**Comment by luizgrp** [comment]
Removed duplicated code in https://github.com/google/horologist/pull/601

**Comment by oas004** [comment]
Sweet! Thanks for looking into this @luizgrp 😄
