### ISSUE TITLE
Data race in DataClient.dataItemFlow(…)

### ISSUE THREAD

**Issue by LouisCAD** [google/horologist#593]
Hello,

As you can see in the snippet below, the code collecting a flow returned by `DataClient.dataItemFlow(…)` can end up on an old value and never receiving the new one.

This would happen if a new value gets generated while the `this@dataItemFlow.getDataItem(uri).await()` call is running, or after, before the `addListener(…)` call completes.

https://github.com/google/horologist/blob/6d75e70311410aa392b509987d9d0d893b7119ab/datalayer/src/main/java/com/google/android/horologist/data/store/impl/DataItemFlow.kt#L53-L57

I can send a PR, should I?

Have a great day!

**Comment by yschimke** [comment]
Yep, please do.
