### ISSUE TITLE
Failing SnackbarHost test

### ISSUE THREAD

**Issue by yschimke** [google/horologist#66]
```
com.google.android.horologist.compose.snackbar.SnackbarHostTest > snackbarHost_returnedResult[test(AVD) - 11] FAILED 
	androidx.compose.ui.test.ComposeTimeoutException: Condition still not satisfied after 5000 ms
	at androidx.compose.ui.test.AndroidComposeTest.waitUntil(ComposeTest.android.kt:218)
```

Have disabled for now in https://github.com/google/horologist/pull/65

**Comment by MohitMandalia** [comment]
SnackbarHost `snackbarHost_returnedResult` issue seems to be resolved I ran the test by removing the `@Ignore` annotation it seems to be passing.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/36087806/178152568-4e4a5c93-e75d-4d03-a51e-3c0fa431a83a.png">

**Comment by yschimke** [comment]
Great, want to put up a PR?

**Comment by yschimke** [comment]
Please complete https://github.com/google/horologist/blob/main/CONTRIBUTING.md#contributor-license-agreement also

**Comment by MohitMandalia** [comment]
sure
This issue was already fixed so i'll just remove the `@Ignore` annotation and make a PR for it.

**Comment by yschimke** [comment]
Tracking in other bug
