### ISSUE TITLE
Paparazzi tests passing for individual PR but failing for main

### ISSUE THREAD

**Issue by luizgrp** [google/horologist#660]
Code of `Title` component was changed in https://github.com/google/horologist/pull/658, and without regenerating the golden image the PR got green build: https://github.com/google/horologist/actions/runs/3189801520.

Then it failed in main: https://github.com/google/horologist/actions/runs/3191099250/jobs/5207004751

```
com.google.android.horologist.media.ui.components.base.TitleTest > withVeryLongText FAILED
    java.lang.AssertionError at TitleTest.kt:49

> Task :media-ui:testDebugUnitTest FAILED
142 tests completed, 1 failed
```

Paparazzi also did NOT fail when running tests locally.

Maybe related: https://github.com/google/horologist/issues/339

**Comment by yschimke** [comment]
Bizarre, when I download the test result artifacts.  They are passing.  So hard to find the problem.

**Comment by luizgrp** [comment]
the reports are in the artifact `snapshot-test-results`, the snapshot tests reports are archived separately in this [step](https://github.com/google/horologist/blob/main/.github/workflows/build.yml#L93) 

```
java.lang.AssertionError: Images differ (by 6.0%) - see details in file:///home/runner/work/horologist/horologist/media-ui/out/failures/delta-com.google.android.horologist.media.ui.components.base_TitleTest_withVeryLongText.png
Thumbnail for current rendering stored at file:///home/runner/work/horologist/horologist/media-ui/out/failures/com.google.android.horologist.media.ui.components.base_TitleTest_withVeryLongText.png
    at org.junit.Assert.fail(Assert.java:89)
```
