### ISSUE TITLE
Add Paparazzi configuration to test UI components without full screen images

### ISSUE THREAD

**Issue by luizgrp** [google/horologist#666]
### WHAT

Address suggestion: https://github.com/google/horologist/pull/648#issuecomment-1263521214

### WHY

In order to reduce the image sizes when testing UI component that are not full screen.

### HOW

- Figure out necessary configuration needed to pass to Paparazzi;
- Add it to reusable configuration, like in [WearPaparazzi](https://github.com/google/horologist/blob/94552e13ea45613cc9b804ee7080b4aa92311d54/paparazzi/src/main/java/com/google/android/horologist/paparazzi/WearPaparazzi.kt#L28);
- Change existing tests to use this configuration and regenerate golden images;

**Comment by yschimke** [comment]
Out of scope
