### ISSUE TITLE
Display playlist download progress in PlaylistDownloadBrowseScreen

### ISSUE THREAD

**Issue by luizgrp** [google/horologist#681]
### WHAT

When a playlist is currently being downloaded, `PlaylistDownloadBrowseScreen` should display its progress:

<img width="259" alt="Screen Shot 2022-10-18 at 13 17 36" src="https://user-images.githubusercontent.com/878134/196427209-cfa971bf-a99d-4eac-adc4-64118634036a.png">

The design is already implemented in:
https://github.com/google/horologist/blob/dfb62736cab49fe5f1f5acfa875e33cbc7c0f193/media-ui/src/main/java/com/google/android/horologist/media/ui/screens/browse/PlaylistDownloadBrowseScreen.kt#L102-L124

But the data [fetched](https://github.com/google/horologist/blob/dfb62736cab49fe5f1f5acfa875e33cbc7c0f193/media-sample/src/main/java/com/google/android/horologist/mediasample/ui/browse/UampBrowseScreenViewModel.kt#L38) in `UampBrowseScreenViewModel` does not have information about the progress to be displayed on the screen, so it always gets [mapped](https://github.com/google/horologist/blob/dfb62736cab49fe5f1f5acfa875e33cbc7c0f193/media-ui/src/main/java/com/google/android/horologist/media/ui/state/mapper/PlaylistDownloadUiModelMapper.kt#L35) to a `PlaylistDownloadUiModel.Completed`.

### WHY

In order to align with Figma specs.

### HOW

Suggested approach:
- Change `UampBrowseScreenViewModel` to use `PlaylistDownloadRepository` to fetch `PlaylistDownload` models, as they contain download information;
- Implement function in `PlaylistDownloadRepository` to return a list of `PlaylistDownload` that are fully downloaded or have at least one download in progress - see implementation in [PlaylistDao](https://github.com/google/horologist/blob/dfb62736cab49fe5f1f5acfa875e33cbc7c0f193/media-data/src/main/java/com/google/android/horologist/media/data/database/dao/PlaylistDao.kt#L71-L85);
- Update `PlaylistDownloadUiModelMapper` to receive a `PlaylistDownload` and return `PlaylistDownloadUiModel` either `InProgress` or `Completed`;

**Comment by yschimke** [comment]
@luizgrp reopen if this is still planned, otherwise closing as stale.
