### ISSUE TITLE
Resume Media Improvement

### ISSUE THREAD

**Issue by laiyichin** [google/horologist#684]
When resuming last played media, there are a few changes we can do to improve the user experience.

- Resume to the last played media, in the playlist, at the last played timeline.
- Resume to the last played media but DO NOT start playing immediately.
- Investigate to store the media play progress on the service (perhaps PlayBackService lifecycle) instead of on the MediaPlayerScreenViewModel, so that the progress could continue to be tracked even when the application goes to the background.

**Comment by yschimke** [comment]
@laiyichin Closing as stale, reopen if still useful.
