### ISSUE TITLE
The compact chip is not clickable on the second page of PagerScreen using horologist 0.1.15

### ISSUE THREAD

**Issue by yingding** [google/horologist#710]
The click event doesn’t seem to be forwarded to the second page of the PagerScreen using `horologist 0.1.15` with `compose 1.3.0` and `wear compose 1.1.0-beta01`

Please find a demo repo reproducing this issue.
https://github.com/yingding/wearChips.git

The same code has worked with `horologist 0.1.14`, `compose 1.2.1` and `wear compose 1.0.2`.

### How to reproduce?
Please switch the `contentList` variable between `contentList_working` to `contentList_not_working`
in the `onCreate()` of the `MainActivity.kt` on the aforementioned [demo repo](https://github.com/yingding/wearChips.git) to see the unintended behaviour.
```kotlin
    override fun onCreate(savedInstanceState: Bundle?) {
        ...
        val contentList = contentList_not_working
       // val contentList = contentList_working
       ...
   }
```

**Comment by yschimke** [comment]
It seems to be edgeSwipeToDismiss that is blocking things. Not specifically CompactChip.

Probably means raising against https://developer.android.com/jetpack/androidx/releases/wear-compose#feedback
