### ISSUE TITLE
datalayer build.gradle linter complains about targetSdk

### ISSUE THREAD

**Issue by fstanis** [google/horologist#712]
This issue seems specific to datalayer/build.gradle since we already have a global linter setting that doesn't seem to be applied there:

https://github.com/google/horologist/blob/8d1b285f5819a9cdc17185217fef4f1bdd1d041b/build.gradle#L205-L213

This seems to prevent CI from being successful so I added an ignore to this file specifically:

https://github.com/google/horologist/blob/9a711a6c66f806e79ae9dabb9659c8891cdf4137/datalayer/build.gradle#L28-L29

Ideally, we should figure out why it's happening and ignore the per-file comment.

**Comment by yschimke** [comment]
There is a bug with new versions of android lint that incorrectly expect wear apps to use targetsdk 33.  The docs are clear that 30 is correct.

**Comment by luizgrp** [comment]
https://b.corp.google.com/issues/196420849

**Comment by luizgrp** [comment]
Fixed by https://github.com/google/horologist/pull/716
