### ISSUE TITLE
Refactor EntityDialog

### ISSUE THREAD

**Issue by laiyichin** [google/horologist#715]
Refactor [EntityDialog](https://github.com/google/horologist/blob/main/media-sample/src/main/java/com/google/android/horologist/mediasample/ui/entity/UampEntityScreen.kt#L166) to move it from UampEntityScreen to [base-ui](https://github.com/google/horologist/tree/main/base-ui/src/debug/java/com/google/android/horologist/base/ui/components) and add [preview](https://github.com/google/horologist/tree/main/base-ui/src/debug/java/com/google/android/horologist/base/ui/components) and [tests](https://github.com/google/horologist/tree/main/base-ui/src/test/java/com/google/android/horologist/base/ui/components).

**Comment by luizgrp** [comment]
Redlines:
![Screen Shot 2022-11-01 at 20 06 28](https://user-images.githubusercontent.com/878134/199330825-751e9060-701f-428e-9a7b-9a52de3bd0b5.png)

Could also rename it, it was called EntityDialog because it was only used in the EntityScreen.

**Comment by luizgrp** [comment]
@laiyichin was this issue fully done in https://github.com/google/horologist/pull/718?

Do you remember if we kept this ticket open because is missing snapshot tests for it?
