### ISSUE TITLE
Add detection for whether volume can be changed

### ISSUE THREAD

**Issue by fstanis** [google/horologist#739]
`MediaRouter` routes have a [`getVolumeHandling()`](https://developer.android.com/reference/androidx/mediarouter/media/MediaRouter.RouteInfo#getVolumeHandling()) which may return [`PLAYBACK_VOLUME_FIXED`](https://developer.android.com/reference/androidx/mediarouter/media/MediaRouter.RouteInfo#PLAYBACK_VOLUME_FIXED()) in which case changing the volume isn't possible. It's not super clear when this happens, i.e. is it even possible for wearable use-cases.

If it is, we should add support for something to the effect of "isVolumeChangeSupported" into our state and disable volume controls when false.

**Comment by fstanis** [comment]
> It's not super clear when this happens, i.e. is it even possible for wearable use-cases.

It seems this is common for something like a Chromecast, as these devices often rely on the TV's own volume that they don't attempt to adjust. So it's definitely not theoretical and Horologist should at least support the possibility of volume adjustment not available (and is thus invisible).

**Comment by yschimke** [comment]
Closing as low priority, reopen if you feel strongly.
