### ISSUE TITLE
Add volume screen previews for locales

### ISSUE THREAD

**Issue by yschimke** [google/horologist#748]
Use a similar approach to WearPreviewThemes which is used in 

```
@WearLargeRoundDevicePreview
@Composable
fun VolumeScreenTheme(
    @PreviewParameter(WearPreviewThemes::class) themeValues: ThemeValues
) {
```

Show all supported languages.

**Comment by oas004** [comment]
Might be me that misunderstands this, but hasn't this been added by the use of the `@WearLocalePreview` ? :) I don't quite see how you can use a `@PreviewParameter` to do this. Am I missing something? :)

**Comment by yschimke** [comment]
Yep fixed in #768

**Comment by yschimke** [comment]
For the parameter it would be using https://github.com/google/accompanist/blob/main/testharness/src/main/java/com/google/accompanist/testharness/TestHarness.kt

**Comment by oas004** [comment]
Ah okay, then it makes sense! Thanks for clarifying 😊
