### ISSUE TITLE
Suggestion: Make it possible to add a brush track colour to ProgressIndicatorSegment

### ISSUE THREAD

**Issue by oas004** [google/horologist#800]
This is just a suggestion. Please feel free to close this if you don't agree :) 

In the current API for the SegmentedProgressIndicator and the SquareSegmentedProgressIndicator composables, the track segments has to be defined as follows

```
public data class ProgressIndicatorSegment(
    val weight: Float,
    val indicatorColor: Color,
    val trackColor: Color? = null,
    val inProgressTrackColor: Color? = null
)
```

I was thinking it could be cool to provide an alternative to this where the indicator colour can be a brush like this:

```
public data class ProgressIndicatorSegment(
    val weight: Float,
    val indicatorColor: Brush,
    val trackColor: Color? = null,
    val inProgressTrackColor: Color? = null
)
```
in addition to the API that already is. Maybe it could be an overriding function or something?

This would make it easy to add a gradient on each of the segments making the "increasing progress" effect independent of the segments themself.
With a change like this, it would be easy to make something like this

![Screenshot 2022-12-04 at 03 46 51](https://user-images.githubusercontent.com/54936943/205471650-f1346d04-092f-4d57-8f0b-6443fde73c4b.png)

Even though you only have 3 segments defined.

What do you think? :)

**Comment by yschimke** [comment]
@garanj thoughts?

This makes sense to me. Are you using this in an app that would use this, or I'd it a general improvement?

**Comment by oas004** [comment]
> @garanj thoughts?
> 
> This makes sense to me. Are you using this in an app that would use this, or I'd it a general improvement?

I was thinking as a general improvement. Just thinking it could look a bit better if the user was using few segments, so could be nice to have this opportunity 😊

**Comment by garanj** [comment]
Sounds great!👍

**Comment by garanj** [comment]
How about for colors applied to individual track segments, could the developer specify different brushes for each?

**Comment by oas004** [comment]
I was thinking maybe if there was an override that took a segment with this api
```
public data class ProgressIndicatorSegment(
    val weight: Float,
    val indicatorColor: Brush,
    val trackColor: Color? = null,
    val inProgressTrackColor: Color? = null
)
```

When calling it you could then in theory have different brushes like this 

```
val previewProgressSections = listOf(
    ProgressIndicatorSegment(
        weight = 3f,
        indicatorColor = Brush.horizontalGradient(listOf(Color.Yellow, Color.Blue))
    ),
    ProgressIndicatorSegment(
        weight = 3f,
        indicatorColor = Brush.linearGradient(listOf(Color.Red, Color.Red, Color.Yellow))
    ),
    ProgressIndicatorSegment(
        weight = 3f,
        indicatorColor = Brush.verticalGradient(listOf(Color.Red, Color.Yellow))
    )
)
```
But I am unsure how it would be to combine colours and brushes. I guess you could have a brush with two of the same colour maybe. If that makes sense? :)

**Comment by yschimke** [comment]
Maybe have the current form as a secondary constructor, but change the field to a Brush.  `SolidColor` seems to be the Brush you want.

**Comment by oas004** [comment]
I think that makes a lot of sense! 😊
