### ISSUE TITLE
Change the way we handle playback position

### ISSUE THREAD

**Issue by fstanis** [google/horologist#806]
Currently, we rely on polling to get position changes from `Player`:

https://github.com/google/horologist/blob/e5924878e69a8ad0a8252abe18ff784ee6d2245c/media-sample/src/main/java/com/google/android/horologist/mediasample/ui/player/MediaPlayerScreenViewModel.kt#L43-L55

There are several disadvantages to this:
- Updates can seem choppy, especially for short media
  - Somewhat mitigated by #798, but this also made the current progress always 1s stale
- Polling logic doesn't live in any component and instead needs to be done manually (as seen in `media-sample` code above)

A better way would be to update position continually, on every animation frame (via [`awaitFrame()`](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-android/kotlinx.coroutines.android/await-frame.html) inside a `LaunchedEffect`). This would mean adding prediction logic that takes into account playback state, speed, last known real position (updated on various existing events) and timestamp of last update + last position.

In effect, this issue means changing `TrackPositionUiModel` to something akin to:

```
public data class TrackPositionUiModel(
    private val playbackSpeed: Float,
    private val position: Long,
    private val duration: Long,
    private val lastUpdatedTimeMillis: Long,
    val showProgress: Boolean
) {
  fun getInferredPosition(currentTimeMillis: Long): Long { ... }
}
```

**Comment by yschimke** [comment]
I do wonder whether Long as a result is enough? If it's got 5 seconds left of playback and getInferredPosition is 10 seconds ahead, what does it return?

What about returning a new value of TrackPositionUiModel with updated position and faked lastUpdatedTimeMillis?

**Comment by fstanis** [comment]
> If it's got 5 seconds left of playback and getInferredPosition is 10 seconds ahead, what does it return?

I'd say `min(inferred, duration)` addresses this? Although it sounds like something seriously went wrong if it's more than 1s off.

> What about returning a new value of TrackPositionUiModel with updated position and faked lastUpdatedTimeMillis?

I'd prefer to separate `TrackPositionUiModel` as holding "real" state from a `Player` from inferred values that are time-based. Also, I think performance matters a lot if we're going to call this for every animation frame, so returning a primitive probably helps.

**Comment by yschimke** [comment]
Sorry, I meant the value passed to getInferredPosition.  MY bad.
