### ISSUE TITLE
Suggestion/question: Make title hideable for Timepicker?

### ISSUE THREAD

**Issue by zelotbe** [google/horologist#815]
Hi,
Is there a way to hide the title for the timepicker? 🙂
If not, maybe there could be an optional parameter?
Currently it shows "Hour", I can't seem to figure out how to hide the string.
Thanks in advance.

![image](https://user-images.githubusercontent.com/19783738/206301501-ebcc66a0-2988-41c2-88ef-4ec8f3251af7.png)

**Comment by yschimke** [comment]
Did you find an answer? Or choose something else?

If you wanted this would you replace the Title with yours?

**Comment by zelotbe** [comment]
> Did you find an answer? Or choose something else?
> 
> If you wanted this would you replace the Title with yours?

Hi, First of all sorry for the late reply.
I realized the title is there for accessibility reasons and decided to keep it. 🙂
