### ISSUE TITLE
Add twitter compose rules check

### ISSUE THREAD

**Issue by luizgrp** [google/horologist#831]
#### WHAT

Change our builds scripts to run [Twitter's Jetpack Compose Rules](https://github.com/twitter/compose-rules).

#### WHY

So issues like https://github.com/google/horologist/pull/830 and https://github.com/google/horologist/pull/611 are detected via code analysis instead of relying on code reviews.

#### HOW

The ideal would be to add the plugin with spotless but [it is not supported](https://twitter.github.io/compose-rules/ktlint/#using-with-spotless). So this ticket is to figure out a good alternative.

---

Below is some context from my findings in https://github.com/google/horologist/pull/610:

Kolinter could be added as temporary measure but [it does not support baselines](https://github.com/jeremymailen/kotlinter-gradle/issues/167). That would force us to fix all the issues in order to add the plugin, which is not great, or suppress each of them with annotations if possible, which is also not great as it would pollute the code.

[Ktlint-gradle](https://twitter.github.io/compose-rules/ktlint/#using-with-ktlint-gradle) could be used, but its version would have to be [downgraded](https://github.com/google/horologist/blob/99599a1ff4aaeed5119595ac25972c6c93fec9a3/gradle/libs.versions.toml#L41) in our project [as the latest version is not currently supported](https://github.com/JLLeitschuh/ktlint-gradle/pull/595). If proceeding with this option, then ktlint would have to be removed from our [spotless configuration](https://github.com/google/horologist/blob/99599a1ff4aaeed5119595ac25972c6c93fec9a3/build.gradle#L116), in order to not run twice.

In overall, if we are going to add a different code analysis tool, I would prefer, if possible, to remove spotless in order to have only a single tool. Our project seems to use [spotless](https://github.com/google/horologist/blob/99599a1ff4aaeed5119595ac25972c6c93fec9a3/build.gradle#L113) for code analysis for the reasons below, so any alternative explored would have to provide the same functionalities:
- [run ktlint](https://github.com/google/horologist/blob/99599a1ff4aaeed5119595ac25972c6c93fec9a3/build.gradle#L116)
- [check license header files](https://github.com/google/horologist/blob/99599a1ff4aaeed5119595ac25972c6c93fec9a3/build.gradle#L117)
- [groovy files formatting](https://github.com/google/horologist/blob/99599a1ff4aaeed5119595ac25972c6c93fec9a3/build.gradle#L122)

**Comment by yschimke** [comment]
Maybe moved to https://github.com/mrmans0n/compose-rules?

**Comment by luizgrp** [comment]
Another alternative setup to try: https://github.com/slackhq/compose-lints/

**Comment by mrmans0n** [comment]
Apparently now ktlint-gradle works well (instead of kotlinter) with the latest ktlint version, if you go the ktlint route. They updated it not so long ago.

**Comment by Goooler** [comment]
This support has been finished in https://github.com/diffplug/spotless/pull/1896, we can try Spotless integration once 6.23.0 is out.

**Comment by yschimke** [comment]
Maybe https://github.com/j-roskopf/ComposeGuard

**Comment by yschimke** [comment]
Closing as low priority, reopen if keen to work on it.
