### ISSUE TITLE
Convert Groovy gradle files to Kotlin DSL

### ISSUE THREAD

**Issue by oas004** [google/horologist#833]
Hey! 

This is just a suggestion and I wanted to know what you guys thought about it. Feel free to close it, if it does not make sense.

I noticed that all the gradle files are in Groovy, what do you guys think about converting it to Kotlin DSL?  I saw that the NowInAndroid app has this, but for instance Accompanist does not. Is there a reason for not converting? :)

**Comment by yschimke** [comment]
I'm for it.

I use kotlin build files exclusively on own projects. Our build came from accompanist, so that's why.

But let's wait for others to weigh in.

**Comment by oas004** [comment]
That makes sense! Will gladly help and contribute if this is something we want :) I agree, let's wait for others to weigh in.

**Comment by luizgrp** [comment]
I'm in! :)

**Comment by oas004** [comment]
Are there more people that needs to weigh in on this? :)

I guess this is something that would be nice to do in multiple PRs?  Is there anything that should be considered when doing this? :)

**Comment by luizgrp** [comment]
I'd recommend reading this [doc](https://docs.gradle.org/current/userguide/migrating_from_groovy_to_kotlin_dsl.html) first, there is a suggestion for [first migration step](https://docs.gradle.org/current/userguide/migrating_from_groovy_to_kotlin_dsl.html#prepare_your_groovy_scripts). 

Multiple small PRs sounds good, if possible, maybe module by module after taking the first migration steps?

**Comment by oas004** [comment]
That sounds great! I think the first step docs you sent me was gold! 🙏😊

**Comment by yschimke** [comment]
Cc @alexvanyo in case you want to share approach for accompanist.
