### ISSUE TITLE
Organize packages of compose-layout module

### ISSUE THREAD

**Issue by luizgrp** [google/horologist#839]
The package structure of [compose-layout](https://github.com/google/horologist/tree/1906b9ccfbc09452cf5b62e75ccfe094f7167f4a/compose-layout) module seems to not be following the pattern seen in other modules of the project, where all the files should be under `com.google.android.horologist.compose.layout` package.

Also [ExperimentalHorologistComposeLayoutApi](https://github.com/google/horologist/blob/1906b9ccfbc09452cf5b62e75ccfe094f7167f4a/compose-layout/src/main/java/com/google/android/horologist/compose/navscaffold/ExperimentalHorologistComposeLayoutApi.kt) annotation is under `com.google.android.horologist.compose.navscaffold` instead of `com.google.android.horologist.compose.layout`.

**Comment by luizgrp** [comment]
@yschimke was this intended? if so I will close the ticket, otherwise I will also raise a ticket for [media3-backend](https://github.com/google/horologist/tree/1906b9ccfbc09452cf5b62e75ccfe094f7167f4a/media3-backend).

**Comment by yschimke** [comment]
I'm a bit concerned about changing the packet. But you are right.

If we go ahead, we should give a headsup that it's coming. Maybe to compose-wear slack? Fix should be easy unless mixing horologist versions

**Comment by yschimke** [comment]
Closing, hasn't been an issue, and will be more disruptive to change.  Reopen if you feel strongly.
