### ISSUE TITLE
Create helper function for paparazzi tests

### ISSUE THREAD

**Issue by luizgrp** [google/horologist#886]
It looks like [a lot](https://github.com/search?q=repo%3Agoogle%2Fhorologist+%22Modifier.background%28Color.Black%29%22+path%3A**%2F*Test.kt&type=code) of our paparazzi tests follow the pattern below of displaying the content inside a `Box`, with black background and centered aligned content:

```kotlin
    @Test
    fun testName() {
        paparazzi.snapshot {
            Box(
                modifier = Modifier.background(Color.Black),
                contentAlignment = Alignment.Center
            ) {
                /* CONTENT HERE */
            }
        }
    }
```

It would be nice if a helper function could be created to simplify the tests code to something like:

```kotlin
    @Test
    fun testName() {
        paparazzi.snapshotInABox {
            /* CONTENT HERE */
        }
    }
```

**Comment by yschimke** [comment]
I guess one question whether they should be smaller, sized automatically to the content instead?

**Comment by luizgrp** [comment]
That's a good point to think about. One more reason to have this function created, once we have a decision made then we will potentially need to only change one place.
