### ISSUE TITLE
Add resourcePrefix to Android modules

### ISSUE THREAD

**Issue by luizgrp** [google/horologist#892]
#### WHAT

Set [resourcePrefix](https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-main:build-system/gradle-api/src/main/java/com/android/build/api/dsl/CommonExtension.kt;l=633?q=CommonExtension) in the Android library modules of the project - unpublished modules and modules for sample apps are not needed.

#### WHY

Avoid naming collisions with similar resources that the consumer defines.

#### HOW

- Add `resourcePrefix = "horologist_"` to `build.gradle.kts`;
- Fix resource names;

**Comment by yschimke** [comment]
Could this break translations?

**Comment by RotBolt** [comment]
Can I pick this up to work or contribute to?

**Comment by luizgrp** [comment]
@RotBolt that would be great!

**Comment by RotBolt** [comment]
I will get started this weekend

**Comment by yschimke** [comment]
I think we have this

**Comment by luizgrp** [comment]
We only have this for newer modules. But happy to close it as low priority.
