### ISSUE TITLE
Fix rotary input in date/time picker samples

### ISSUE THREAD

**Issue by luizgrp** [google/horologist#894]
The rotary input does not work when the demos for `TimePicker` and `DatePicker` in the sample app are initially launched.
Tapping on the current selected unit does not make it work. In order to make it work the user needs to select a different unit than the initial selected unit.

#### Steps to reproduce

1. In the sample app, tap on one of the chips under "Composables" below:
    - [Time Picker](https://github.com/google/horologist/blob/473d4976c0f4912953082a16797d17258c3f5e97/sample/src/main/java/com/google/android/horologist/sample/SampleWearApp.kt#L140-L150)
    - [Date Picker](https://github.com/google/horologist/blob/473d4976c0f4912953082a16797d17258c3f5e97/sample/src/main/java/com/google/android/horologist/sample/SampleWearApp.kt#L129-L139)
    - [Time with Seconds Picker](https://github.com/google/horologist/blob/473d4976c0f4912953082a16797d17258c3f5e97/sample/src/main/java/com/google/android/horologist/sample/SampleWearApp.kt#L151-L161)
    - [Time without Seconds Picker](https://github.com/google/horologist/blob/473d4976c0f4912953082a16797d17258c3f5e97/sample/src/main/java/com/google/android/horologist/sample/SampleWearApp.kt#L162-L173)

2. Without tapping anywhere on the screen, use the rotary input;

PS: rotary input can be [used](https://developer.android.com/training/wearables/user-input/rotary-input#emulator) on an emulator.

##### Expected behaviour

The picker should change the values of the selected unit.

##### Actual behaviour

The picker does not change the values of the selected unit.

##### Recovery steps

1. Tap on a different unit (minutes, month, etc);
2. Use the rotary input;

**Comment by yschimke** [comment]
Presumably, this is a bug in the library code, not the sample. It should work automatically.
