### ISSUE TITLE
(Re-)add persisting media position in settings

### ISSUE THREAD

**Issue by fstanis** [google/horologist#900]
It seems #806 (via #841) will inevitably break #810: because position will now be predictive most of the time, this block of code will lose its home:

https://github.com/google/horologist/blob/b04b8360a42078c9f607101fdbe1b25f6c94c676/media-sample/src/main/java/com/google/android/horologist/mediasample/ui/player/MediaPlayerScreenViewModel.kt#L55-L61

I'm not sure how this should be done properly. Two options are:
- Persist on certain events, such as state changes like pause.
- Persist on service lifecycle (e.g. via `onDestroy`).
- Persist on activity lifecycle (e.g. via `onPause`).

The first option seems easiest, but wouldn't persist changes on things like app crashes.

**Comment by yschimke** [comment]
I think the first for now. Its also a sample

**Comment by yschimke** [comment]
Closing for now.  Low priority.
