### ISSUE TITLE
Release 0.2.6 seems broken

### ISSUE THREAD

**Issue by yschimke** [google/horologist#905]
Probably due to recent bumps

Compare https://repo1.maven.org/maven2/com/google/android/horologist/horologist-audio-ui/0.2.6/

to

https://repo1.maven.org/maven2/com/google/android/horologist/horologist-audio-ui/0.2.5/

**Comment by yschimke** [comment]
Maybe related to https://github.com/google/horologist/pull/889, but not sure why it's failing.  Will try bumping to 0.2.2 and test locally.

**Comment by luizgrp** [comment]
[0.2.7](https://github.com/google/horologist/releases/tag/v0.2.7) released as fix.
