### ISSUE TITLE
Use previews as examples in our docs

### ISSUE THREAD

**Issue by fstanis** [google/horologist#918]
Currently, many of our docs don't have any examples e.g. [composables](https://google.github.io/horologist/composables/). We can probably leverage our previews and use them as code samples - they're guaranteed to build and usually serve as good examples.

Seems we can use [mkdocs-codeinclude-plugin](https://github.com/rnorth/mkdocs-codeinclude-plugin) to make this process automatic.

**Comment by yschimke** [comment]
Closing as low priority, reopen if keen to work on it.
