### ISSUE TITLE
Improve docs for scrollable/belowTimeText

### ISSUE THREAD

**Issue by yingding** [google/horologist#919]
The TimeText in WearNavScaffold/scrollable can
1. Not be scrolled down in a ScalingLazyColumn with 3 items
2. overlays with a two line Text in a ScalingLazyColumn with 3 items

# Issue description
More detailed issue description and horologist version can be found at:
https://github.com/yingding/timeText/blob/main/README.md 

# Issues Sample Repo
The repository code reproduce this issue can be found at 
https://github.com/yingding/timeText

# Reproduce the two issues
In the `MainActivity.kt` Preview `Devices.WEAR_OS_SMALL_ROUND` and interactive mode, the time text issues can be seen.

**Comment by yingding** [comment]
@yschimke Thanks for looking into this

**Comment by yschimke** [comment]
I think it's more a documentation/usage bug.  Thanks for flagging it.

Try this PR https://github.com/yingding/timeText/pull/1

**Comment by yschimke** [comment]
Raised https://github.com/google/horologist/issues/924 for square layout issue
