### ISSUE TITLE
Add snapshot tests for AlertDialogAlert

### ISSUE THREAD

**Issue by luizgrp** [google/horologist#927]
Add snapshot tests for [AlertDialogAlert](https://github.com/google/horologist/blob/8f70f64d7c18358839ef5620381b6206bf085c59/base-ui/src/main/java/com/google/android/horologist/base/ui/components/AlertDialog.kt#L69) component which was added in https://github.com/google/horologist/pull/718. An attempt to add the tests was made in that PR but the snapshots were all generated with blank content. 

I think we might have to implement a solution for `ScalingLazyListState` similar to what was done for `ScalingLazyColumnState ` with [PositionedState](https://github.com/google/horologist/blob/main/media-ui/src/test/java/com/google/android/horologist/media/ui/components/PositionedState.kt) and pass that as param to `scrollState` param in `Alert` component from compose material.

**Comment by yschimke** [comment]
Closing as low priority.
