### ISSUE TITLE
Start using Kotlin 1.8 and Compose compiler version 1.4.0

### ISSUE THREAD

**Issue by oas004** [google/horologist#929]
Hi, would it be cool to update the project to use Kotlin 1.8 and target the Compose compiler version 1.4.0? 

Wanted to have a discussion with you guys on this before trying to do the bump :) 

Is there any known reason not to do this?

**Comment by yschimke** [comment]
No, it should be safe. Libraries like okhttp/okio have already moved to 1.8.0

https://github.com/square/okio/blob/master/CHANGELOG.md#version-330

Any risk of things breaking is useful information, let's wait for a second opinion though.

**Comment by oas004** [comment]
That sounds like a good idea!

**Comment by yschimke** [comment]
I suepect you'll need this to avoid conflict between kotlin-stdlin:1.8.0 and kotlin-stdlib-jdk8:1.7.x

    constraints {
        implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.0") {
            because("kotlin-stdlib-jdk7 is now a part of kotlin-stdlib")
        }
        implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.0") {
            because("kotlin-stdlib-jdk8 is now a part of kotlin-stdlib")
        }
    }
