### ISSUE TITLE
Feature Request for `ScalingLazyColumnDefaults.belowTimeText` and `ScalingLazyColumnState` 

### ISSUE THREAD

**Issue by yingding** [google/horologist#931]
For the horologist `0.2.7`
```kotlin
@ExperimentalHorologistComposeLayoutApi
public class ScalingLazyColumnState(
    ...
    public val contentPadding: PaddingValues = PaddingValues(horizontal = 10.dp),
```
The `contentPadding` is implemented with `val`, can we change that to `var`?

This will allow developer to do some adjustment for the SLC

```kotlin
    ScalingLazyColumn(
        modifier = modifier.fillMaxSize(),
        columnState = columnState.apply {
            contentPadding = PaddingValues(horizontal = 6.dp)
        }
    )
```
It would also be possible to extend `contentPadding` in the factory method in `ScalingLazyColumnDefaults`. I don't know which would be a better choice.

**Comment by yschimke** [comment]
As discussed in kotlinlang slack:

> It can't be a var, it needs to be immutable. So we should pass it in.  I'd prefer to add an optional param.  I'm happy to do that.
> 
> Before jumping to that, can you give a screenshot, or show in that existing sample project, what you need it for.
> 
> The idea of ScalingLazyColumnDefaults.belowTimeText is meant to be that it does the right thing without a lot of tuning params.  Any counter examples, I'd like to understand why it's breaking.

**Comment by yingding** [comment]
The Square Watchface supported is small than a small round watch face, so that without reducing the SLC contentPadding, my text in an app card is wrapped. My text font is set to be 12.sp, 11.sp would be too small to read on a larger screen.
![Screenshot 2023-01-18 at 18 00 22](https://user-images.githubusercontent.com/1073701/213253564-06020348-ba8f-4c4a-9f90-cadff86fa888.png)

If it is possible, I would also like to be able to reduce the `toPaddingDp` local variable of `belowTimeText` method
```
val topPaddingDp = 32.dp + (if (firstItemIsFullWidth) 20.dp else 0.dp)
```
For a graph element with head text is the `topPaddingDp > 32.dp` to large, it looks away to many viewports and the graph element can not be centred by autoCentering of SLC well.
 
![Screenshot 2023-01-18 at 18 03 39](https://user-images.githubusercontent.com/1073701/213255401-ff6dad41-5769-4e30-8056-cf7570e795a9.png)

**Comment by yschimke** [comment]
Both of those sounds reasonable tuning without breaking the formulas.
