### ISSUE TITLE
Bump Paparazzi to 1.2

### ISSUE THREAD

**Issue by oas004** [google/horologist#932]
I guess since Paparazzi released https://github.com/cashapp/paparazzi/releases/tag/1.2.0 does that mean we can use the cash app version of paparazzi and not Chris Banes' (dev.chrisbanes.paparazzi:paparazzi-gradle-plugin:1.1.0-sdk33-alpha02) anymore? :)

**Comment by oas004** [comment]
I'm not 100% sure, but I might need #928 before this can pass

**Comment by yschimke** [comment]
For now, why not include that in your PR.  Will help test that change also.

**Comment by oas004** [comment]
Rebased it on main now as it got merged, but it seems like I have some failures with the a11y tests, so I have to look more into that

**Comment by yschimke** [comment]
I'm happy to look into those before we land, unless you want to see the horrors.

**Comment by oas004** [comment]
I tried to look into it a bit, but could not quite figure it out. If you have time, please go ahead. Would love to see the changes though to learn what the issues where if you find out though :)
