### ISSUE TITLE
layout glitch when downloading

### ISSUE THREAD

**Issue by yschimke** [google/horologist#964]
![image](https://user-images.githubusercontent.com/231923/215501379-70b5ed6a-a0c3-404d-b288-0bf7fe8123cf.png)

**Comment by yschimke** [comment]
Bisected to https://github.com/google/horologist/pull/935

**Comment by yschimke** [comment]
Caught by paparazzi

![image](https://user-images.githubusercontent.com/231923/215566527-f25b85b4-9b23-47d4-be76-dd39aeab10b7.png)

**Comment by luizgrp** [comment]
why 935 did not fail if it was caught by paparazzi?

**Comment by yschimke** [comment]
Probably only a slight change?
