### ISSUE TITLE
Why still managing kotlin stdlib?

### ISSUE THREAD

**Issue by CoreFloDev** [google/horologist#968]
Hi,

Is there a particular reason for explicitly declaring the use of stdlib in all the project?
https://github.com/google/horologist/blob/main/auth-sample-wear/build.gradle.kts#L120
https://github.com/google/horologist/blob/main/audio/build.gradle.kts#L100
https://github.com/google/horologist/blob/main/media-data/build.gradle.kts#L87
etc...

Since Kotlin 1.4, that dependencies is added automatically by the plugin according to the Kotlin version and java version used
https://kotlinlang.org/docs/whatsnew14.html#dependency-on-the-standard-library-added-by-default

Thanks,

**Comment by yschimke** [comment]
Care to submit a PR to remove.

We are also pinning stdlib jdk7 and 8 in order to avoid failures in release builds because of transitive dependencies. Is there a good fiz for that?

**Comment by CoreFloDev** [comment]
I don't understand that bit

> We are also pinning stdlib jdk7 and 8 in order to avoid failures in release builds because of transitive dependencies

Could you please give me more context about it?

Thanks!

**Comment by yschimke** [comment]
https://youtrack.jetbrains.com/issue/KT-55297/kotlin-stdlib-should-declare-constraints-on-kotlin-stdlib-jdk8-and-kotlin-stdlib-jdk7

**Comment by yschimke** [comment]
We should probably switch to the BOM

    implementation(platform("org.jetbrains.kotlin:kotlin-bom:1.8.10"))
