### ISSUE TITLE
Use gradle build scan and check if the build really needs more memory

### ISSUE THREAD

**Issue by yschimke** [google/horologist#984]
we could try [gradle build scan](https://scans.gradle.com/) and check if the build really [needs more memory](https://docs.gradle.com/enterprise/tutorials/performance-build-scans/#determine_if_your_build_needs_more_memory)

_Originally posted by @luizgrp in https://github.com/google/horologist/issues/983#issuecomment-1415788768_

**Comment by luizgrp** [comment]
[publish docs](https://github.com/google/horologist/actions/workflows/publish-docs.yml) workflow [failed](https://github.com/google/horologist/actions/runs/4302880751/jobs/7501929919) with OutOfMemoryError:

```
e: java.lang.OutOfMemoryError: Metaspace

	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
> Task :network-awareness:kspReleaseKotlin FAILED
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)

...


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':network-awareness:kspReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Not enough memory to run compilation. Try to increase it via 'gradle.properties':
     org.gradle.jvmargs=-Xmx<size>

...


Caused by: org.jetbrains.kotlin.gradle.tasks.OOMErrorException: Not enough memory to run compilation. Try to increase it via 'gradle.properties':
org.gradle.jvmargs=-Xmx<size>
	at org.jetbrains.kotlin.gradle.tasks.TasksUtilsKt.throwExceptionIfCompilationFailed(tasksUtils.kt:34)

```

**Comment by luizgrp** [comment]
This should be fixed in https://github.com/google/horologist/pull/1102 - will wait until next release before closing the issue.

**Comment by luizgrp** [comment]
Docs published after release: https://github.com/google/horologist/actions/runs/4424480195
